apiVersion: 1

datasources:
  - name: C4ISR Prometheus
    uid: c4isr-prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false

  - name: C4ISR Loki
    uid: c4isr-loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: false
