// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: alerts.sql

package dbgen

import (
	"context"
)

const acknowledgeAlert = `-- name: AcknowledgeAlert :one
UPDATE alerts
SET state = 'ACKNOWLEDGED', acknowledged_at = now(), acknowledged_by = $1, updated_at = now()
WHERE id = $2 AND state = 'ACTIVE'
RETURNING id, type, severity, state, title, message, source_reference, track_id, asset_id, geofence_id, incident_id, created_at, updated_at, acknowledged_at, acknowledged_by, resolved_at, resolved_by
`

type AcknowledgeAlertParams struct {
	AcknowledgedBy *string
	ID             string
}

func (q *Queries) AcknowledgeAlert(ctx context.Context, arg AcknowledgeAlertParams) (Alert, error) {
	row := q.db.QueryRow(ctx, acknowledgeAlert, arg.AcknowledgedBy, arg.ID)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Severity,
		&i.State,
		&i.Title,
		&i.Message,
		&i.SourceReference,
		&i.TrackID,
		&i.AssetID,
		&i.GeofenceID,
		&i.IncidentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AcknowledgedAt,
		&i.AcknowledgedBy,
		&i.ResolvedAt,
		&i.ResolvedBy,
	)
	return i, err
}

const countActiveAlerts = `-- name: CountActiveAlerts :one
SELECT count(*) FROM alerts WHERE state = 'ACTIVE'
`

func (q *Queries) CountActiveAlerts(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveAlerts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAlerts = `-- name: CountAlerts :one
SELECT count(*) FROM alerts
WHERE ($1::text IS NULL OR state = $1)
  AND ($2::text IS NULL OR severity = $2)
  AND ($3::text IS NULL OR track_id = $3)
  AND ($4::text IS NULL OR incident_id = $4)
`

type CountAlertsParams struct {
	State      *string
	Severity   *string
	TrackID    *string
	IncidentID *string
}

func (q *Queries) CountAlerts(ctx context.Context, arg CountAlertsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAlerts,
		arg.State,
		arg.Severity,
		arg.TrackID,
		arg.IncidentID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAlert = `-- name: CreateAlert :one
INSERT INTO alerts (
    id, type, severity, state, title, message, source_reference,
    track_id, asset_id, geofence_id, incident_id, created_at, updated_at
) VALUES (
    $1, $2, $3, 'ACTIVE', $4, $5, $6,
    $7, $8, $9, $10, now(), now()
)
RETURNING id, type, severity, state, title, message, source_reference, track_id, asset_id, geofence_id, incident_id, created_at, updated_at, acknowledged_at, acknowledged_by, resolved_at, resolved_by
`

type CreateAlertParams struct {
	ID              string
	Type            string
	Severity        string
	Title           string
	Message         *string
	SourceReference []byte
	TrackID         *string
	AssetID         *string
	GeofenceID      *string
	IncidentID      *string
}

func (q *Queries) CreateAlert(ctx context.Context, arg CreateAlertParams) (Alert, error) {
	row := q.db.QueryRow(ctx, createAlert,
		arg.ID,
		arg.Type,
		arg.Severity,
		arg.Title,
		arg.Message,
		arg.SourceReference,
		arg.TrackID,
		arg.AssetID,
		arg.GeofenceID,
		arg.IncidentID,
	)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Severity,
		&i.State,
		&i.Title,
		&i.Message,
		&i.SourceReference,
		&i.TrackID,
		&i.AssetID,
		&i.GeofenceID,
		&i.IncidentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AcknowledgedAt,
		&i.AcknowledgedBy,
		&i.ResolvedAt,
		&i.ResolvedBy,
	)
	return i, err
}

const findUnresolvedAlertForGeofenceTrack = `-- name: FindUnresolvedAlertForGeofenceTrack :one
SELECT id, type, severity, state, title, message, source_reference, track_id, asset_id, geofence_id, incident_id, created_at, updated_at, acknowledged_at, acknowledged_by, resolved_at, resolved_by FROM alerts
WHERE geofence_id = $1 AND track_id = $2 AND state <> 'RESOLVED'
ORDER BY created_at DESC
LIMIT 1
`

type FindUnresolvedAlertForGeofenceTrackParams struct {
	GeofenceID *string
	TrackID    *string
}

func (q *Queries) FindUnresolvedAlertForGeofenceTrack(ctx context.Context, arg FindUnresolvedAlertForGeofenceTrackParams) (Alert, error) {
	row := q.db.QueryRow(ctx, findUnresolvedAlertForGeofenceTrack, arg.GeofenceID, arg.TrackID)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Severity,
		&i.State,
		&i.Title,
		&i.Message,
		&i.SourceReference,
		&i.TrackID,
		&i.AssetID,
		&i.GeofenceID,
		&i.IncidentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AcknowledgedAt,
		&i.AcknowledgedBy,
		&i.ResolvedAt,
		&i.ResolvedBy,
	)
	return i, err
}

const getAlert = `-- name: GetAlert :one
SELECT id, type, severity, state, title, message, source_reference, track_id, asset_id, geofence_id, incident_id, created_at, updated_at, acknowledged_at, acknowledged_by, resolved_at, resolved_by FROM alerts WHERE id = $1
`

func (q *Queries) GetAlert(ctx context.Context, id string) (Alert, error) {
	row := q.db.QueryRow(ctx, getAlert, id)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Severity,
		&i.State,
		&i.Title,
		&i.Message,
		&i.SourceReference,
		&i.TrackID,
		&i.AssetID,
		&i.GeofenceID,
		&i.IncidentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AcknowledgedAt,
		&i.AcknowledgedBy,
		&i.ResolvedAt,
		&i.ResolvedBy,
	)
	return i, err
}

const listAlerts = `-- name: ListAlerts :many
SELECT id, type, severity, state, title, message, source_reference, track_id, asset_id, geofence_id, incident_id, created_at, updated_at, acknowledged_at, acknowledged_by, resolved_at, resolved_by FROM alerts
WHERE ($1::text IS NULL OR state = $1)
  AND ($2::text IS NULL OR severity = $2)
  AND ($3::text IS NULL OR track_id = $3)
  AND ($4::text IS NULL OR incident_id = $4)
ORDER BY created_at DESC
LIMIT $6 OFFSET $5
`

type ListAlertsParams struct {
	State       *string
	Severity    *string
	TrackID     *string
	IncidentID  *string
	OffsetCount int32
	LimitCount  int32
}

func (q *Queries) ListAlerts(ctx context.Context, arg ListAlertsParams) ([]Alert, error) {
	rows, err := q.db.Query(ctx, listAlerts,
		arg.State,
		arg.Severity,
		arg.TrackID,
		arg.IncidentID,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Alert{}
	for rows.Next() {
		var i Alert
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Severity,
			&i.State,
			&i.Title,
			&i.Message,
			&i.SourceReference,
			&i.TrackID,
			&i.AssetID,
			&i.GeofenceID,
			&i.IncidentID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AcknowledgedAt,
			&i.AcknowledgedBy,
			&i.ResolvedAt,
			&i.ResolvedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlertsByIncident = `-- name: ListAlertsByIncident :many
SELECT id, type, severity, state, title, message, source_reference, track_id, asset_id, geofence_id, incident_id, created_at, updated_at, acknowledged_at, acknowledged_by, resolved_at, resolved_by FROM alerts WHERE incident_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListAlertsByIncident(ctx context.Context, incidentID *string) ([]Alert, error) {
	rows, err := q.db.Query(ctx, listAlertsByIncident, incidentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Alert{}
	for rows.Next() {
		var i Alert
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Severity,
			&i.State,
			&i.Title,
			&i.Message,
			&i.SourceReference,
			&i.TrackID,
			&i.AssetID,
			&i.GeofenceID,
			&i.IncidentID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AcknowledgedAt,
			&i.AcknowledgedBy,
			&i.ResolvedAt,
			&i.ResolvedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveAlert = `-- name: ResolveAlert :one
UPDATE alerts
SET state = 'RESOLVED', resolved_at = now(), resolved_by = $1, updated_at = now()
WHERE id = $2 AND state IN ('ACTIVE', 'ACKNOWLEDGED')
RETURNING id, type, severity, state, title, message, source_reference, track_id, asset_id, geofence_id, incident_id, created_at, updated_at, acknowledged_at, acknowledged_by, resolved_at, resolved_by
`

type ResolveAlertParams struct {
	ResolvedBy *string
	ID         string
}

func (q *Queries) ResolveAlert(ctx context.Context, arg ResolveAlertParams) (Alert, error) {
	row := q.db.QueryRow(ctx, resolveAlert, arg.ResolvedBy, arg.ID)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Severity,
		&i.State,
		&i.Title,
		&i.Message,
		&i.SourceReference,
		&i.TrackID,
		&i.AssetID,
		&i.GeofenceID,
		&i.IncidentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AcknowledgedAt,
		&i.AcknowledgedBy,
		&i.ResolvedAt,
		&i.ResolvedBy,
	)
	return i, err
}

const setAlertIncident = `-- name: SetAlertIncident :exec
UPDATE alerts SET incident_id = $1, updated_at = now() WHERE id = $2
`

type SetAlertIncidentParams struct {
	IncidentID *string
	ID         string
}

func (q *Queries) SetAlertIncident(ctx context.Context, arg SetAlertIncidentParams) error {
	_, err := q.db.Exec(ctx, setAlertIncident, arg.IncidentID, arg.ID)
	return err
}
