// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: assets.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assetExists = `-- name: AssetExists :one
SELECT EXISTS (SELECT 1 FROM assets WHERE id = $1)
`

func (q *Queries) AssetExists(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRow(ctx, assetExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countAssets = `-- name: CountAssets :one
SELECT count(*) FROM assets
`

func (q *Queries) CountAssets(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAssets)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAsset = `-- name: CreateAsset :one
INSERT INTO assets (id, name, type, status, capabilities, metadata, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, now(), now())
RETURNING id, name, type, status, capabilities, metadata, created_at, updated_at
`

type CreateAssetParams struct {
	ID           string
	Name         string
	Type         string
	Status       string
	Capabilities []byte
	Metadata     []byte
}

func (q *Queries) CreateAsset(ctx context.Context, arg CreateAssetParams) (Asset, error) {
	row := q.db.QueryRow(ctx, createAsset,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.Status,
		arg.Capabilities,
		arg.Metadata,
	)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Status,
		&i.Capabilities,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ensureAssetState = `-- name: EnsureAssetState :exec
INSERT INTO asset_state (asset_id, connection_state)
VALUES ($1, 'unknown')
ON CONFLICT (asset_id) DO NOTHING
`

func (q *Queries) EnsureAssetState(ctx context.Context, assetID string) error {
	_, err := q.db.Exec(ctx, ensureAssetState, assetID)
	return err
}

const getAsset = `-- name: GetAsset :one
SELECT id, name, type, status, capabilities, metadata, created_at, updated_at FROM assets WHERE id = $1
`

func (q *Queries) GetAsset(ctx context.Context, id string) (Asset, error) {
	row := q.db.QueryRow(ctx, getAsset, id)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Status,
		&i.Capabilities,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAssetDetail = `-- name: GetAssetDetail :one
SELECT
    a.id, a.name, a.type, a.status, a.capabilities, a.metadata, a.created_at, a.updated_at,
    s.health, s.connection_state, s.last_seen_at, s.speed AS state_speed, s.heading AS state_heading,
    (s.position IS NOT NULL)::boolean AS has_position,
    COALESCE(ST_Y(s.position::geometry), 0)::float8 AS lat,
    COALESCE(ST_X(s.position::geometry), 0)::float8 AS lng
FROM assets a
LEFT JOIN asset_state s ON s.asset_id = a.id
WHERE a.id = $1
`

type GetAssetDetailRow struct {
	ID              string
	Name            string
	Type            string
	Status          string
	Capabilities    []byte
	Metadata        []byte
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	Health          *string
	ConnectionState *string
	LastSeenAt      pgtype.Timestamptz
	StateSpeed      *float64
	StateHeading    *float64
	HasPosition     bool
	Lat             float64
	Lng             float64
}

func (q *Queries) GetAssetDetail(ctx context.Context, id string) (GetAssetDetailRow, error) {
	row := q.db.QueryRow(ctx, getAssetDetail, id)
	var i GetAssetDetailRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Status,
		&i.Capabilities,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Health,
		&i.ConnectionState,
		&i.LastSeenAt,
		&i.StateSpeed,
		&i.StateHeading,
		&i.HasPosition,
		&i.Lat,
		&i.Lng,
	)
	return i, err
}

const getAssetState = `-- name: GetAssetState :one
SELECT
    asset_id, speed, heading, health, connection_state, last_seen_at, updated_at,
    (position IS NOT NULL)::boolean AS has_position,
    COALESCE(ST_Y(position::geometry), 0)::float8 AS lat,
    COALESCE(ST_X(position::geometry), 0)::float8 AS lng
FROM asset_state
WHERE asset_id = $1
`

type GetAssetStateRow struct {
	AssetID         string
	Speed           *float64
	Heading         *float64
	Health          *string
	ConnectionState string
	LastSeenAt      pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	HasPosition     bool
	Lat             float64
	Lng             float64
}

func (q *Queries) GetAssetState(ctx context.Context, assetID string) (GetAssetStateRow, error) {
	row := q.db.QueryRow(ctx, getAssetState, assetID)
	var i GetAssetStateRow
	err := row.Scan(
		&i.AssetID,
		&i.Speed,
		&i.Heading,
		&i.Health,
		&i.ConnectionState,
		&i.LastSeenAt,
		&i.UpdatedAt,
		&i.HasPosition,
		&i.Lat,
		&i.Lng,
	)
	return i, err
}

const listAssets = `-- name: ListAssets :many
SELECT id, name, type, status, capabilities, metadata, created_at, updated_at FROM assets
ORDER BY created_at DESC
LIMIT $2 OFFSET $1
`

type ListAssetsParams struct {
	OffsetCount int32
	LimitCount  int32
}

func (q *Queries) ListAssets(ctx context.Context, arg ListAssetsParams) ([]Asset, error) {
	rows, err := q.db.Query(ctx, listAssets, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Asset{}
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Status,
			&i.Capabilities,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssetsWithState = `-- name: ListAssetsWithState :many
SELECT
    a.id, a.name, a.type, a.status, a.capabilities, a.metadata, a.created_at, a.updated_at,
    s.health, s.connection_state, s.last_seen_at, s.speed AS state_speed, s.heading AS state_heading,
    (s.position IS NOT NULL)::boolean AS has_position,
    COALESCE(ST_Y(s.position::geometry), 0)::float8 AS lat,
    COALESCE(ST_X(s.position::geometry), 0)::float8 AS lng
FROM assets a
LEFT JOIN asset_state s ON s.asset_id = a.id
ORDER BY a.name
LIMIT $2 OFFSET $1
`

type ListAssetsWithStateParams struct {
	OffsetCount int32
	LimitCount  int32
}

type ListAssetsWithStateRow struct {
	ID              string
	Name            string
	Type            string
	Status          string
	Capabilities    []byte
	Metadata        []byte
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	Health          *string
	ConnectionState *string
	LastSeenAt      pgtype.Timestamptz
	StateSpeed      *float64
	StateHeading    *float64
	HasPosition     bool
	Lat             float64
	Lng             float64
}

func (q *Queries) ListAssetsWithState(ctx context.Context, arg ListAssetsWithStateParams) ([]ListAssetsWithStateRow, error) {
	rows, err := q.db.Query(ctx, listAssetsWithState, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAssetsWithStateRow{}
	for rows.Next() {
		var i ListAssetsWithStateRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Status,
			&i.Capabilities,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Health,
			&i.ConnectionState,
			&i.LastSeenAt,
			&i.StateSpeed,
			&i.StateHeading,
			&i.HasPosition,
			&i.Lat,
			&i.Lng,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleAssetIDs = `-- name: ListStaleAssetIDs :many
SELECT a.id AS asset_id
FROM assets AS a
LEFT JOIN asset_state AS s ON s.asset_id = a.id
WHERE a.created_at < $1
  AND (s.last_seen_at IS NULL OR s.last_seen_at < $1)
`

func (q *Queries) ListStaleAssetIDs(ctx context.Context, cutoff pgtype.Timestamptz) ([]string, error) {
	rows, err := q.db.Query(ctx, listStaleAssetIDs, cutoff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var asset_id string
		if err := rows.Scan(&asset_id); err != nil {
			return nil, err
		}
		items = append(items, asset_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAssetStatus = `-- name: UpdateAssetStatus :one
UPDATE assets
SET status = $1, updated_at = now()
WHERE id = $2
RETURNING id, name, type, status, capabilities, metadata, created_at, updated_at
`

type UpdateAssetStatusParams struct {
	Status string
	ID     string
}

func (q *Queries) UpdateAssetStatus(ctx context.Context, arg UpdateAssetStatusParams) (Asset, error) {
	row := q.db.QueryRow(ctx, updateAssetStatus, arg.Status, arg.ID)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Status,
		&i.Capabilities,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertAssetState = `-- name: UpsertAssetState :one
WITH applied AS (
INSERT INTO asset_state (
    asset_id, position, speed, heading, health, connection_state, last_seen_at, updated_at
) VALUES (
    $1,
    CASE WHEN $2::boolean
         THEN ST_SetSRID(ST_MakePoint($3::float8, $4::float8), 4326)::geography
         ELSE NULL END,
    $5, $6, $7, $8, $9, now()
)
ON CONFLICT (asset_id) DO UPDATE SET
    position = CASE WHEN $2::boolean THEN EXCLUDED.position ELSE asset_state.position END,
    speed = COALESCE(EXCLUDED.speed, asset_state.speed),
    heading = COALESCE(EXCLUDED.heading, asset_state.heading),
    health = COALESCE(EXCLUDED.health, asset_state.health),
    connection_state = COALESCE(EXCLUDED.connection_state, asset_state.connection_state),
    last_seen_at = EXCLUDED.last_seen_at,
    updated_at = now()
WHERE (
    (
        $10::timestamptz IS NULL
        AND asset_state.last_seen_at IS NULL
    )
    OR asset_state.last_seen_at = $10::timestamptz
)
AND (
    asset_state.last_seen_at IS NULL
    OR asset_state.last_seen_at < EXCLUDED.last_seen_at
)
RETURNING asset_id
)
SELECT EXISTS (SELECT 1 FROM applied)::boolean AS applied
`

type UpsertAssetStateParams struct {
	AssetID            string
	HasPosition        bool
	Lng                float64
	Lat                float64
	Speed              *float64
	Heading            *float64
	Health             *string
	ConnectionState    string
	ObservedAt         pgtype.Timestamptz
	ExpectedLastSeenAt pgtype.Timestamptz
}

func (q *Queries) UpsertAssetState(ctx context.Context, arg UpsertAssetStateParams) (bool, error) {
	row := q.db.QueryRow(ctx, upsertAssetState,
		arg.AssetID,
		arg.HasPosition,
		arg.Lng,
		arg.Lat,
		arg.Speed,
		arg.Heading,
		arg.Health,
		arg.ConnectionState,
		arg.ObservedAt,
		arg.ExpectedLastSeenAt,
	)
	var applied bool
	err := row.Scan(&applied)
	return applied, err
}
