// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: assessments.sql

package dbgen

import (
	"context"
)

const addAssessmentEvidence = `-- name: AddAssessmentEvidence :exec
INSERT INTO assessment_evidence (assessment_id, evidence_type, evidence_id)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type AddAssessmentEvidenceParams struct {
	AssessmentID string
	EvidenceType string
	EvidenceID   string
}

func (q *Queries) AddAssessmentEvidence(ctx context.Context, arg AddAssessmentEvidenceParams) error {
	_, err := q.db.Exec(ctx, addAssessmentEvidence, arg.AssessmentID, arg.EvidenceType, arg.EvidenceID)
	return err
}

const countAssessments = `-- name: CountAssessments :one
SELECT count(*) FROM assessments
WHERE ($1::text IS NULL OR subject_type = $1)
  AND ($2::text IS NULL OR subject_id = $2)
`

type CountAssessmentsParams struct {
	SubjectType *string
	SubjectID   *string
}

func (q *Queries) CountAssessments(ctx context.Context, arg CountAssessmentsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAssessments, arg.SubjectType, arg.SubjectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAssessment = `-- name: CreateAssessment :one
INSERT INTO assessments (
    id, subject_type, subject_id, type, conclusion, confidence, method, created_by, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, now()
)
RETURNING id, subject_type, subject_id, type, conclusion, confidence, method, created_by, created_at
`

type CreateAssessmentParams struct {
	ID          string
	SubjectType string
	SubjectID   string
	Type        string
	Conclusion  string
	Confidence  *float64
	Method      string
	CreatedBy   *string
}

func (q *Queries) CreateAssessment(ctx context.Context, arg CreateAssessmentParams) (Assessment, error) {
	row := q.db.QueryRow(ctx, createAssessment,
		arg.ID,
		arg.SubjectType,
		arg.SubjectID,
		arg.Type,
		arg.Conclusion,
		arg.Confidence,
		arg.Method,
		arg.CreatedBy,
	)
	var i Assessment
	err := row.Scan(
		&i.ID,
		&i.SubjectType,
		&i.SubjectID,
		&i.Type,
		&i.Conclusion,
		&i.Confidence,
		&i.Method,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getAssessment = `-- name: GetAssessment :one
SELECT id, subject_type, subject_id, type, conclusion, confidence, method, created_by, created_at FROM assessments WHERE id = $1
`

func (q *Queries) GetAssessment(ctx context.Context, id string) (Assessment, error) {
	row := q.db.QueryRow(ctx, getAssessment, id)
	var i Assessment
	err := row.Scan(
		&i.ID,
		&i.SubjectType,
		&i.SubjectID,
		&i.Type,
		&i.Conclusion,
		&i.Confidence,
		&i.Method,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listAssessmentEvidence = `-- name: ListAssessmentEvidence :many
SELECT assessment_id, evidence_type, evidence_id, added_at
FROM assessment_evidence
WHERE assessment_id = $1
ORDER BY added_at ASC
`

func (q *Queries) ListAssessmentEvidence(ctx context.Context, assessmentID string) ([]AssessmentEvidence, error) {
	rows, err := q.db.Query(ctx, listAssessmentEvidence, assessmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AssessmentEvidence{}
	for rows.Next() {
		var i AssessmentEvidence
		if err := rows.Scan(
			&i.AssessmentID,
			&i.EvidenceType,
			&i.EvidenceID,
			&i.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssessments = `-- name: ListAssessments :many
SELECT id, subject_type, subject_id, type, conclusion, confidence, method, created_by, created_at FROM assessments
WHERE ($1::text IS NULL OR subject_type = $1)
  AND ($2::text IS NULL OR subject_id = $2)
ORDER BY created_at DESC
LIMIT $4 OFFSET $3
`

type ListAssessmentsParams struct {
	SubjectType *string
	SubjectID   *string
	OffsetCount int32
	LimitCount  int32
}

func (q *Queries) ListAssessments(ctx context.Context, arg ListAssessmentsParams) ([]Assessment, error) {
	rows, err := q.db.Query(ctx, listAssessments,
		arg.SubjectType,
		arg.SubjectID,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Assessment{}
	for rows.Next() {
		var i Assessment
		if err := rows.Scan(
			&i.ID,
			&i.SubjectType,
			&i.SubjectID,
			&i.Type,
			&i.Conclusion,
			&i.Confidence,
			&i.Method,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
