// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAuditEvents = `-- name: CountAuditEvents :one
SELECT count(*) FROM audit_events
WHERE ($1::text IS NULL OR subject_type = $1)
  AND ($2::text IS NULL OR subject_id = $2)
  AND ($3::text IS NULL OR action = $3)
  AND ($4::timestamptz IS NULL OR occurred_at >= $4)
`

type CountAuditEventsParams struct {
	SubjectType *string
	SubjectID   *string
	Action      *string
	Since       pgtype.Timestamptz
}

func (q *Queries) CountAuditEvents(ctx context.Context, arg CountAuditEventsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditEvents,
		arg.SubjectType,
		arg.SubjectID,
		arg.Action,
		arg.Since,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuditEvent = `-- name: CreateAuditEvent :one
INSERT INTO audit_events (
    id, occurred_at, actor_type, actor_id, action,
    subject_type, subject_id, correlation_id, data, created_at
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, now()
)
RETURNING id, occurred_at, actor_type, actor_id, action, subject_type, subject_id, correlation_id, data, created_at
`

type CreateAuditEventParams struct {
	ID            string
	OccurredAt    pgtype.Timestamptz
	ActorType     string
	ActorID       *string
	Action        string
	SubjectType   *string
	SubjectID     *string
	CorrelationID *string
	Data          []byte
}

func (q *Queries) CreateAuditEvent(ctx context.Context, arg CreateAuditEventParams) (AuditEvent, error) {
	row := q.db.QueryRow(ctx, createAuditEvent,
		arg.ID,
		arg.OccurredAt,
		arg.ActorType,
		arg.ActorID,
		arg.Action,
		arg.SubjectType,
		arg.SubjectID,
		arg.CorrelationID,
		arg.Data,
	)
	var i AuditEvent
	err := row.Scan(
		&i.ID,
		&i.OccurredAt,
		&i.ActorType,
		&i.ActorID,
		&i.Action,
		&i.SubjectType,
		&i.SubjectID,
		&i.CorrelationID,
		&i.Data,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditEvents = `-- name: ListAuditEvents :many
SELECT id, occurred_at, actor_type, actor_id, action, subject_type, subject_id, correlation_id, data, created_at FROM audit_events
WHERE ($1::text IS NULL OR subject_type = $1)
  AND ($2::text IS NULL OR subject_id = $2)
  AND ($3::text IS NULL OR action = $3)
  AND ($4::timestamptz IS NULL OR occurred_at >= $4)
ORDER BY occurred_at DESC, id DESC
LIMIT $6 OFFSET $5
`

type ListAuditEventsParams struct {
	SubjectType *string
	SubjectID   *string
	Action      *string
	Since       pgtype.Timestamptz
	OffsetCount int32
	LimitCount  int32
}

func (q *Queries) ListAuditEvents(ctx context.Context, arg ListAuditEventsParams) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, listAuditEvents,
		arg.SubjectType,
		arg.SubjectID,
		arg.Action,
		arg.Since,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditEvent{}
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.OccurredAt,
			&i.ActorType,
			&i.ActorID,
			&i.Action,
			&i.SubjectType,
			&i.SubjectID,
			&i.CorrelationID,
			&i.Data,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
