// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: classifications.sql

package dbgen

import (
	"context"
)

const createClassification = `-- name: CreateClassification :one
INSERT INTO classifications (
    id, track_id, label, confidence, method, source_reference, created_by, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, now()
)
RETURNING id, track_id, label, confidence, method, source_reference, created_by, created_at
`

type CreateClassificationParams struct {
	ID              string
	TrackID         string
	Label           string
	Confidence      *float64
	Method          string
	SourceReference *string
	CreatedBy       *string
}

func (q *Queries) CreateClassification(ctx context.Context, arg CreateClassificationParams) (Classification, error) {
	row := q.db.QueryRow(ctx, createClassification,
		arg.ID,
		arg.TrackID,
		arg.Label,
		arg.Confidence,
		arg.Method,
		arg.SourceReference,
		arg.CreatedBy,
	)
	var i Classification
	err := row.Scan(
		&i.ID,
		&i.TrackID,
		&i.Label,
		&i.Confidence,
		&i.Method,
		&i.SourceReference,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getClassification = `-- name: GetClassification :one
SELECT id, track_id, label, confidence, method, source_reference, created_by, created_at FROM classifications WHERE id = $1
`

func (q *Queries) GetClassification(ctx context.Context, id string) (Classification, error) {
	row := q.db.QueryRow(ctx, getClassification, id)
	var i Classification
	err := row.Scan(
		&i.ID,
		&i.TrackID,
		&i.Label,
		&i.Confidence,
		&i.Method,
		&i.SourceReference,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const latestClassificationForTrack = `-- name: LatestClassificationForTrack :one
SELECT id, track_id, label, confidence, method, source_reference, created_by, created_at FROM classifications
WHERE track_id = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) LatestClassificationForTrack(ctx context.Context, trackID string) (Classification, error) {
	row := q.db.QueryRow(ctx, latestClassificationForTrack, trackID)
	var i Classification
	err := row.Scan(
		&i.ID,
		&i.TrackID,
		&i.Label,
		&i.Confidence,
		&i.Method,
		&i.SourceReference,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listClassificationsByTrack = `-- name: ListClassificationsByTrack :many
SELECT id, track_id, label, confidence, method, source_reference, created_by, created_at FROM classifications
WHERE track_id = $1
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type ListClassificationsByTrackParams struct {
	TrackID     string
	OffsetCount int32
	LimitCount  int32
}

func (q *Queries) ListClassificationsByTrack(ctx context.Context, arg ListClassificationsByTrackParams) ([]Classification, error) {
	rows, err := q.db.Query(ctx, listClassificationsByTrack, arg.TrackID, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Classification{}
	for rows.Next() {
		var i Classification
		if err := rows.Scan(
			&i.ID,
			&i.TrackID,
			&i.Label,
			&i.Confidence,
			&i.Method,
			&i.SourceReference,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
