// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: commands.sql

package dbgen

import (
	"context"
)

const countCommands = `-- name: CountCommands :one
SELECT count(*) FROM commands
WHERE ($1::text IS NULL OR asset_id = $1)
  AND ($2::text IS NULL OR state = $2)
  AND ($3::text IS NULL OR mission_id = $3)
`

type CountCommandsParams struct {
	AssetID   *string
	State     *string
	MissionID *string
}

func (q *Queries) CountCommands(ctx context.Context, arg CountCommandsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCommands, arg.AssetID, arg.State, arg.MissionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCommand = `-- name: CreateCommand :one
INSERT INTO commands (
    id, asset_id, mission_id, incident_id, type, payload, state,
    created_by, correlation_id, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, now(), now()
)
RETURNING id, asset_id, mission_id, incident_id, type, payload, state, created_by, correlation_id, created_at, updated_at, queued_at, sent_at, acknowledged_at, completed_at, failure_reason
`

type CreateCommandParams struct {
	ID            string
	AssetID       string
	MissionID     *string
	IncidentID    *string
	Type          string
	Payload       []byte
	State         string
	CreatedBy     *string
	CorrelationID *string
}

func (q *Queries) CreateCommand(ctx context.Context, arg CreateCommandParams) (Command, error) {
	row := q.db.QueryRow(ctx, createCommand,
		arg.ID,
		arg.AssetID,
		arg.MissionID,
		arg.IncidentID,
		arg.Type,
		arg.Payload,
		arg.State,
		arg.CreatedBy,
		arg.CorrelationID,
	)
	var i Command
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.MissionID,
		&i.IncidentID,
		&i.Type,
		&i.Payload,
		&i.State,
		&i.CreatedBy,
		&i.CorrelationID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.QueuedAt,
		&i.SentAt,
		&i.AcknowledgedAt,
		&i.CompletedAt,
		&i.FailureReason,
	)
	return i, err
}

const getCommand = `-- name: GetCommand :one
SELECT id, asset_id, mission_id, incident_id, type, payload, state, created_by, correlation_id, created_at, updated_at, queued_at, sent_at, acknowledged_at, completed_at, failure_reason FROM commands WHERE id = $1
`

func (q *Queries) GetCommand(ctx context.Context, id string) (Command, error) {
	row := q.db.QueryRow(ctx, getCommand, id)
	var i Command
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.MissionID,
		&i.IncidentID,
		&i.Type,
		&i.Payload,
		&i.State,
		&i.CreatedBy,
		&i.CorrelationID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.QueuedAt,
		&i.SentAt,
		&i.AcknowledgedAt,
		&i.CompletedAt,
		&i.FailureReason,
	)
	return i, err
}

const listCommands = `-- name: ListCommands :many
SELECT id, asset_id, mission_id, incident_id, type, payload, state, created_by, correlation_id, created_at, updated_at, queued_at, sent_at, acknowledged_at, completed_at, failure_reason FROM commands
WHERE ($1::text IS NULL OR asset_id = $1)
  AND ($2::text IS NULL OR state = $2)
  AND ($3::text IS NULL OR mission_id = $3)
ORDER BY created_at DESC
LIMIT $5 OFFSET $4
`

type ListCommandsParams struct {
	AssetID     *string
	State       *string
	MissionID   *string
	OffsetCount int32
	LimitCount  int32
}

func (q *Queries) ListCommands(ctx context.Context, arg ListCommandsParams) ([]Command, error) {
	rows, err := q.db.Query(ctx, listCommands,
		arg.AssetID,
		arg.State,
		arg.MissionID,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Command{}
	for rows.Next() {
		var i Command
		if err := rows.Scan(
			&i.ID,
			&i.AssetID,
			&i.MissionID,
			&i.IncidentID,
			&i.Type,
			&i.Payload,
			&i.State,
			&i.CreatedBy,
			&i.CorrelationID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.QueuedAt,
			&i.SentAt,
			&i.AcknowledgedAt,
			&i.CompletedAt,
			&i.FailureReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const transitionCommand = `-- name: TransitionCommand :one
UPDATE commands
SET state = $1,
    updated_at = now(),
    queued_at = CASE WHEN $1::text = 'QUEUED' AND queued_at IS NULL THEN now() ELSE queued_at END,
    sent_at = CASE WHEN $1::text = 'SENT' AND sent_at IS NULL THEN now() ELSE sent_at END,
    acknowledged_at = CASE WHEN $1::text = 'ACKNOWLEDGED' AND acknowledged_at IS NULL THEN now() ELSE acknowledged_at END,
    completed_at = CASE WHEN $1::text = 'COMPLETED' AND completed_at IS NULL THEN now() ELSE completed_at END,
    failure_reason = CASE WHEN $1::text IN ('REJECTED', 'FAILED', 'TIMED_OUT')
                          THEN $2 ELSE failure_reason END
WHERE id = $3
RETURNING id, asset_id, mission_id, incident_id, type, payload, state, created_by, correlation_id, created_at, updated_at, queued_at, sent_at, acknowledged_at, completed_at, failure_reason
`

type TransitionCommandParams struct {
	State         string
	FailureReason *string
	ID            string
}

func (q *Queries) TransitionCommand(ctx context.Context, arg TransitionCommandParams) (Command, error) {
	row := q.db.QueryRow(ctx, transitionCommand, arg.State, arg.FailureReason, arg.ID)
	var i Command
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.MissionID,
		&i.IncidentID,
		&i.Type,
		&i.Payload,
		&i.State,
		&i.CreatedBy,
		&i.CorrelationID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.QueuedAt,
		&i.SentAt,
		&i.AcknowledgedAt,
		&i.CompletedAt,
		&i.FailureReason,
	)
	return i, err
}
