// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: geofences.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countGeofences = `-- name: CountGeofences :one
SELECT count(*) FROM geofences
`

func (q *Queries) CountGeofences(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countGeofences)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGeofence = `-- name: CreateGeofence :one
INSERT INTO geofences (id, name, type, geometry, severity, active, metadata, created_at, updated_at)
VALUES (
    $1, $2, $3,
    ST_SetSRID(ST_GeomFromGeoJSON($4::text), 4326),
    $5, $6, $7, now(), now()
)
RETURNING
    id, name, type, severity, active, metadata, created_at, updated_at,
    ST_AsGeoJSON(geometry)::text AS geojson
`

type CreateGeofenceParams struct {
	ID       string
	Name     string
	Type     string
	Geojson  string
	Severity string
	Active   bool
	Metadata []byte
}

type CreateGeofenceRow struct {
	ID        string
	Name      string
	Type      string
	Severity  string
	Active    bool
	Metadata  []byte
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	Geojson   string
}

func (q *Queries) CreateGeofence(ctx context.Context, arg CreateGeofenceParams) (CreateGeofenceRow, error) {
	row := q.db.QueryRow(ctx, createGeofence,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.Geojson,
		arg.Severity,
		arg.Active,
		arg.Metadata,
	)
	var i CreateGeofenceRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Severity,
		&i.Active,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Geojson,
	)
	return i, err
}

const deleteGeofenceStateForTrack = `-- name: DeleteGeofenceStateForTrack :exec
DELETE FROM geofence_states WHERE track_id = $1
`

func (q *Queries) DeleteGeofenceStateForTrack(ctx context.Context, trackID string) error {
	_, err := q.db.Exec(ctx, deleteGeofenceStateForTrack, trackID)
	return err
}

const getGeofence = `-- name: GetGeofence :one
SELECT
    id, name, type, severity, active, metadata, created_at, updated_at,
    ST_AsGeoJSON(geometry)::text AS geojson
FROM geofences
WHERE id = $1
`

type GetGeofenceRow struct {
	ID        string
	Name      string
	Type      string
	Severity  string
	Active    bool
	Metadata  []byte
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	Geojson   string
}

func (q *Queries) GetGeofence(ctx context.Context, id string) (GetGeofenceRow, error) {
	row := q.db.QueryRow(ctx, getGeofence, id)
	var i GetGeofenceRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Severity,
		&i.Active,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Geojson,
	)
	return i, err
}

const getGeofenceState = `-- name: GetGeofenceState :one
SELECT geofence_id, track_id, inside, since, updated_at
FROM geofence_states
WHERE geofence_id = $1 AND track_id = $2
`

type GetGeofenceStateParams struct {
	GeofenceID string
	TrackID    string
}

func (q *Queries) GetGeofenceState(ctx context.Context, arg GetGeofenceStateParams) (GeofenceState, error) {
	row := q.db.QueryRow(ctx, getGeofenceState, arg.GeofenceID, arg.TrackID)
	var i GeofenceState
	err := row.Scan(
		&i.GeofenceID,
		&i.TrackID,
		&i.Inside,
		&i.Since,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveGeofencesContainingPoint = `-- name: ListActiveGeofencesContainingPoint :many
SELECT
    id, name, type, severity, active, metadata, created_at, updated_at,
    ST_AsGeoJSON(geometry)::text AS geojson
FROM geofences
WHERE active = true
  AND ST_Contains(geometry, ST_SetSRID(ST_MakePoint($1::float8, $2::float8), 4326))
ORDER BY created_at DESC
`

type ListActiveGeofencesContainingPointParams struct {
	Lng float64
	Lat float64
}

type ListActiveGeofencesContainingPointRow struct {
	ID        string
	Name      string
	Type      string
	Severity  string
	Active    bool
	Metadata  []byte
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	Geojson   string
}

func (q *Queries) ListActiveGeofencesContainingPoint(ctx context.Context, arg ListActiveGeofencesContainingPointParams) ([]ListActiveGeofencesContainingPointRow, error) {
	rows, err := q.db.Query(ctx, listActiveGeofencesContainingPoint, arg.Lng, arg.Lat)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveGeofencesContainingPointRow{}
	for rows.Next() {
		var i ListActiveGeofencesContainingPointRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Severity,
			&i.Active,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Geojson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGeofenceStatesByTrack = `-- name: ListGeofenceStatesByTrack :many
SELECT geofence_id, track_id, inside, since, updated_at
FROM geofence_states
WHERE track_id = $1
`

func (q *Queries) ListGeofenceStatesByTrack(ctx context.Context, trackID string) ([]GeofenceState, error) {
	rows, err := q.db.Query(ctx, listGeofenceStatesByTrack, trackID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GeofenceState{}
	for rows.Next() {
		var i GeofenceState
		if err := rows.Scan(
			&i.GeofenceID,
			&i.TrackID,
			&i.Inside,
			&i.Since,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGeofences = `-- name: ListGeofences :many
SELECT
    id, name, type, severity, active, metadata, created_at, updated_at,
    ST_AsGeoJSON(geometry)::text AS geojson
FROM geofences
ORDER BY created_at DESC
LIMIT $2 OFFSET $1
`

type ListGeofencesParams struct {
	OffsetCount int32
	LimitCount  int32
}

type ListGeofencesRow struct {
	ID        string
	Name      string
	Type      string
	Severity  string
	Active    bool
	Metadata  []byte
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	Geojson   string
}

func (q *Queries) ListGeofences(ctx context.Context, arg ListGeofencesParams) ([]ListGeofencesRow, error) {
	rows, err := q.db.Query(ctx, listGeofences, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGeofencesRow{}
	for rows.Next() {
		var i ListGeofencesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Severity,
			&i.Active,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Geojson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reconcileGeofenceStates = `-- name: ReconcileGeofenceStates :many
WITH locked AS (
    SELECT pg_advisory_xact_lock(hashtext($1::text)) AS acquired
), eligible AS (
    SELECT 1
    FROM tracks t
    CROSS JOIN locked
    WHERE t.id = $1
      AND $2::timestamptz >= t.last_seen_at
), existing AS (
    SELECT gs.geofence_id, gs.inside
    FROM geofence_states gs
    CROSS JOIN locked
    CROSS JOIN eligible
    WHERE gs.track_id = $1
      AND ($3::text = '' OR gs.geofence_id LIKE $3::text || '%')
    FOR UPDATE
), containing AS (
    SELECT DISTINCT id
    FROM unnest($4::text[]) AS ids(id)
), entered AS (
    INSERT INTO geofence_states (geofence_id, track_id, inside, since, updated_at)
    SELECT c.id, $1, true, now(), now()
    FROM containing c
    CROSS JOIN locked
    CROSS JOIN eligible
    ON CONFLICT (geofence_id, track_id) DO UPDATE SET
        inside = EXCLUDED.inside,
        since = now(),
        updated_at = now()
    WHERE geofence_states.inside IS DISTINCT FROM EXCLUDED.inside
    RETURNING geofence_id, inside
), exited AS (
    UPDATE geofence_states gs
    SET inside = false,
        since = now(),
        updated_at = now()
    FROM existing e
    WHERE gs.geofence_id = e.geofence_id
      AND gs.track_id = $1
      AND e.inside
      AND NOT EXISTS (SELECT 1 FROM containing c WHERE c.id = e.geofence_id)
    RETURNING gs.geofence_id, gs.inside
)
SELECT geofence_id, inside FROM entered
UNION ALL
SELECT geofence_id, inside FROM exited
ORDER BY geofence_id
`

type ReconcileGeofenceStatesParams struct {
	TrackID       string
	ObservedAt    pgtype.Timestamptz
	ScopePrefix   string
	ContainingIds []string
}

type ReconcileGeofenceStatesRow struct {
	GeofenceID string
	Inside     bool
}

func (q *Queries) ReconcileGeofenceStates(ctx context.Context, arg ReconcileGeofenceStatesParams) ([]ReconcileGeofenceStatesRow, error) {
	rows, err := q.db.Query(ctx, reconcileGeofenceStates,
		arg.TrackID,
		arg.ObservedAt,
		arg.ScopePrefix,
		arg.ContainingIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReconcileGeofenceStatesRow{}
	for rows.Next() {
		var i ReconcileGeofenceStatesRow
		if err := rows.Scan(&i.GeofenceID, &i.Inside); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGeofenceActive = `-- name: UpdateGeofenceActive :one
UPDATE geofences
SET active = $1, updated_at = now()
WHERE id = $2
RETURNING id, name, type, severity, active, metadata, created_at, updated_at,
    ST_AsGeoJSON(geometry)::text AS geojson
`

type UpdateGeofenceActiveParams struct {
	Active bool
	ID     string
}

type UpdateGeofenceActiveRow struct {
	ID        string
	Name      string
	Type      string
	Severity  string
	Active    bool
	Metadata  []byte
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	Geojson   string
}

func (q *Queries) UpdateGeofenceActive(ctx context.Context, arg UpdateGeofenceActiveParams) (UpdateGeofenceActiveRow, error) {
	row := q.db.QueryRow(ctx, updateGeofenceActive, arg.Active, arg.ID)
	var i UpdateGeofenceActiveRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Severity,
		&i.Active,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Geojson,
	)
	return i, err
}

const upsertGeofenceState = `-- name: UpsertGeofenceState :exec
INSERT INTO geofence_states (geofence_id, track_id, inside, since, updated_at)
VALUES ($1, $2, $3, now(), now())
ON CONFLICT (geofence_id, track_id) DO UPDATE SET
    inside = EXCLUDED.inside,
    since = CASE WHEN geofence_states.inside IS DISTINCT FROM EXCLUDED.inside
                 THEN now() ELSE geofence_states.since END,
    updated_at = now()
`

type UpsertGeofenceStateParams struct {
	GeofenceID string
	TrackID    string
	Inside     bool
}

func (q *Queries) UpsertGeofenceState(ctx context.Context, arg UpsertGeofenceStateParams) error {
	_, err := q.db.Exec(ctx, upsertGeofenceState, arg.GeofenceID, arg.TrackID, arg.Inside)
	return err
}
