// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: geospatial.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listAssetsWithinRadius = `-- name: ListAssetsWithinRadius :many
SELECT
    a.id, a.name, a.type, a.status,
    s.connection_state, s.last_seen_at,
    (s.position IS NOT NULL)::boolean AS has_position,
    COALESCE(ST_Y(s.position::geometry), 0)::float8 AS lat,
    COALESCE(ST_X(s.position::geometry), 0)::float8 AS lng,
    ST_Distance(
        s.position,
        ST_SetSRID(ST_MakePoint($1::float8, $2::float8), 4326)::geography
    )::float8 AS distance_m
FROM assets a
JOIN asset_state s ON s.asset_id = a.id
WHERE s.position IS NOT NULL
  AND ST_DWithin(
        s.position,
        ST_SetSRID(ST_MakePoint($1::float8, $2::float8), 4326)::geography,
        $3::float8
      )
ORDER BY distance_m ASC
LIMIT $4
`

type ListAssetsWithinRadiusParams struct {
	Lng        float64
	Lat        float64
	RadiusM    float64
	LimitCount int32
}

type ListAssetsWithinRadiusRow struct {
	ID              string
	Name            string
	Type            string
	Status          string
	ConnectionState string
	LastSeenAt      pgtype.Timestamptz
	HasPosition     bool
	Lat             float64
	Lng             float64
	DistanceM       float64
}

func (q *Queries) ListAssetsWithinRadius(ctx context.Context, arg ListAssetsWithinRadiusParams) ([]ListAssetsWithinRadiusRow, error) {
	rows, err := q.db.Query(ctx, listAssetsWithinRadius,
		arg.Lng,
		arg.Lat,
		arg.RadiusM,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAssetsWithinRadiusRow{}
	for rows.Next() {
		var i ListAssetsWithinRadiusRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Status,
			&i.ConnectionState,
			&i.LastSeenAt,
			&i.HasPosition,
			&i.Lat,
			&i.Lng,
			&i.DistanceM,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nearestAssets = `-- name: NearestAssets :many
SELECT
    a.id, a.name, a.type, a.status,
    s.connection_state, s.last_seen_at,
    (s.position IS NOT NULL)::boolean AS has_position,
    COALESCE(ST_Y(s.position::geometry), 0)::float8 AS lat,
    COALESCE(ST_X(s.position::geometry), 0)::float8 AS lng,
    ST_Distance(
        s.position,
        ST_SetSRID(ST_MakePoint($1::float8, $2::float8), 4326)::geography
    )::float8 AS distance_m
FROM assets a
JOIN asset_state s ON s.asset_id = a.id
WHERE s.position IS NOT NULL
ORDER BY distance_m ASC
LIMIT $3
`

type NearestAssetsParams struct {
	Lng        float64
	Lat        float64
	LimitCount int32
}

type NearestAssetsRow struct {
	ID              string
	Name            string
	Type            string
	Status          string
	ConnectionState string
	LastSeenAt      pgtype.Timestamptz
	HasPosition     bool
	Lat             float64
	Lng             float64
	DistanceM       float64
}

func (q *Queries) NearestAssets(ctx context.Context, arg NearestAssetsParams) ([]NearestAssetsRow, error) {
	rows, err := q.db.Query(ctx, nearestAssets, arg.Lng, arg.Lat, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NearestAssetsRow{}
	for rows.Next() {
		var i NearestAssetsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Status,
			&i.ConnectionState,
			&i.LastSeenAt,
			&i.HasPosition,
			&i.Lat,
			&i.Lng,
			&i.DistanceM,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
