// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: incidents.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addIncidentAlert = `-- name: AddIncidentAlert :exec
INSERT INTO incident_alerts (incident_id, alert_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddIncidentAlertParams struct {
	IncidentID string
	AlertID    string
}

func (q *Queries) AddIncidentAlert(ctx context.Context, arg AddIncidentAlertParams) error {
	_, err := q.db.Exec(ctx, addIncidentAlert, arg.IncidentID, arg.AlertID)
	return err
}

const addIncidentAssessment = `-- name: AddIncidentAssessment :exec
INSERT INTO incident_assessments (incident_id, assessment_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddIncidentAssessmentParams struct {
	IncidentID   string
	AssessmentID string
}

func (q *Queries) AddIncidentAssessment(ctx context.Context, arg AddIncidentAssessmentParams) error {
	_, err := q.db.Exec(ctx, addIncidentAssessment, arg.IncidentID, arg.AssessmentID)
	return err
}

const addIncidentAsset = `-- name: AddIncidentAsset :exec
INSERT INTO incident_assets (incident_id, asset_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddIncidentAssetParams struct {
	IncidentID string
	AssetID    string
}

func (q *Queries) AddIncidentAsset(ctx context.Context, arg AddIncidentAssetParams) error {
	_, err := q.db.Exec(ctx, addIncidentAsset, arg.IncidentID, arg.AssetID)
	return err
}

const addIncidentObservation = `-- name: AddIncidentObservation :exec
INSERT INTO incident_observations (incident_id, observation_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddIncidentObservationParams struct {
	IncidentID    string
	ObservationID string
}

func (q *Queries) AddIncidentObservation(ctx context.Context, arg AddIncidentObservationParams) error {
	_, err := q.db.Exec(ctx, addIncidentObservation, arg.IncidentID, arg.ObservationID)
	return err
}

const addIncidentTrack = `-- name: AddIncidentTrack :exec
INSERT INTO incident_tracks (incident_id, track_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddIncidentTrackParams struct {
	IncidentID string
	TrackID    string
}

func (q *Queries) AddIncidentTrack(ctx context.Context, arg AddIncidentTrackParams) error {
	_, err := q.db.Exec(ctx, addIncidentTrack, arg.IncidentID, arg.TrackID)
	return err
}

const countIncidents = `-- name: CountIncidents :one
SELECT count(*) FROM incidents
WHERE ($1::text IS NULL OR status = $1)
`

func (q *Queries) CountIncidents(ctx context.Context, status *string) (int64, error) {
	row := q.db.QueryRow(ctx, countIncidents, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createIncident = `-- name: CreateIncident :one
INSERT INTO incidents (
    id, title, description, priority, status, assigned_operator, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, now(), now()
)
RETURNING id, title, description, priority, status, assigned_operator, created_at, updated_at, resolved_at, closed_at
`

type CreateIncidentParams struct {
	ID               string
	Title            string
	Description      string
	Priority         string
	Status           string
	AssignedOperator *string
}

func (q *Queries) CreateIncident(ctx context.Context, arg CreateIncidentParams) (Incident, error) {
	row := q.db.QueryRow(ctx, createIncident,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Priority,
		arg.Status,
		arg.AssignedOperator,
	)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Priority,
		&i.Status,
		&i.AssignedOperator,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResolvedAt,
		&i.ClosedAt,
	)
	return i, err
}

const getIncident = `-- name: GetIncident :one
SELECT id, title, description, priority, status, assigned_operator, created_at, updated_at, resolved_at, closed_at FROM incidents WHERE id = $1
`

func (q *Queries) GetIncident(ctx context.Context, id string) (Incident, error) {
	row := q.db.QueryRow(ctx, getIncident, id)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Priority,
		&i.Status,
		&i.AssignedOperator,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResolvedAt,
		&i.ClosedAt,
	)
	return i, err
}

const listIncidentAlerts = `-- name: ListIncidentAlerts :many
SELECT a.id, a.type, a.severity, a.state, a.title, a.message, a.source_reference, a.track_id, a.asset_id, a.geofence_id, a.incident_id, a.created_at, a.updated_at, a.acknowledged_at, a.acknowledged_by, a.resolved_at, a.resolved_by FROM alerts a
JOIN incident_alerts ia ON ia.alert_id = a.id
WHERE ia.incident_id = $1
ORDER BY a.created_at DESC
`

func (q *Queries) ListIncidentAlerts(ctx context.Context, incidentID string) ([]Alert, error) {
	rows, err := q.db.Query(ctx, listIncidentAlerts, incidentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Alert{}
	for rows.Next() {
		var i Alert
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Severity,
			&i.State,
			&i.Title,
			&i.Message,
			&i.SourceReference,
			&i.TrackID,
			&i.AssetID,
			&i.GeofenceID,
			&i.IncidentID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AcknowledgedAt,
			&i.AcknowledgedBy,
			&i.ResolvedAt,
			&i.ResolvedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncidentAssessments = `-- name: ListIncidentAssessments :many
SELECT a.id, a.subject_type, a.subject_id, a.type, a.conclusion, a.confidence, a.method, a.created_by, a.created_at
FROM assessments a
JOIN incident_assessments ia ON ia.assessment_id = a.id
WHERE ia.incident_id = $1
ORDER BY a.created_at DESC
`

func (q *Queries) ListIncidentAssessments(ctx context.Context, incidentID string) ([]Assessment, error) {
	rows, err := q.db.Query(ctx, listIncidentAssessments, incidentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Assessment{}
	for rows.Next() {
		var i Assessment
		if err := rows.Scan(
			&i.ID,
			&i.SubjectType,
			&i.SubjectID,
			&i.Type,
			&i.Conclusion,
			&i.Confidence,
			&i.Method,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncidentAssets = `-- name: ListIncidentAssets :many
SELECT
    a.id, a.name, a.type, a.status, a.capabilities, a.created_at, a.updated_at,
    s.health, s.connection_state, s.last_seen_at, s.speed AS state_speed, s.heading AS state_heading,
    (s.position IS NOT NULL)::boolean AS has_position,
    COALESCE(ST_Y(s.position::geometry), 0)::float8 AS lat,
    COALESCE(ST_X(s.position::geometry), 0)::float8 AS lng
FROM assets a
JOIN incident_assets ia ON ia.asset_id = a.id
LEFT JOIN asset_state s ON s.asset_id = a.id
WHERE ia.incident_id = $1
ORDER BY a.name
`

type ListIncidentAssetsRow struct {
	ID              string
	Name            string
	Type            string
	Status          string
	Capabilities    []byte
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	Health          *string
	ConnectionState *string
	LastSeenAt      pgtype.Timestamptz
	StateSpeed      *float64
	StateHeading    *float64
	HasPosition     bool
	Lat             float64
	Lng             float64
}

func (q *Queries) ListIncidentAssets(ctx context.Context, incidentID string) ([]ListIncidentAssetsRow, error) {
	rows, err := q.db.Query(ctx, listIncidentAssets, incidentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIncidentAssetsRow{}
	for rows.Next() {
		var i ListIncidentAssetsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Status,
			&i.Capabilities,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Health,
			&i.ConnectionState,
			&i.LastSeenAt,
			&i.StateSpeed,
			&i.StateHeading,
			&i.HasPosition,
			&i.Lat,
			&i.Lng,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncidentObservations = `-- name: ListIncidentObservations :many
SELECT
    o.id, o.source_id, o.observation_type, o.observed_at, o.received_at, o.processed_at,
    o.payload, o.quality, o.track_hint, o.created_at,
    (o.position IS NOT NULL)::boolean AS has_position,
    COALESCE(ST_Y(o.position::geometry), 0)::float8 AS lat,
    COALESCE(ST_X(o.position::geometry), 0)::float8 AS lng
FROM observations o
JOIN incident_observations io ON io.observation_id = o.id
WHERE io.incident_id = $1
ORDER BY o.observed_at DESC
LIMIT $2
`

type ListIncidentObservationsParams struct {
	IncidentID string
	LimitCount int32
}

type ListIncidentObservationsRow struct {
	ID              string
	SourceID        string
	ObservationType string
	ObservedAt      pgtype.Timestamptz
	ReceivedAt      pgtype.Timestamptz
	ProcessedAt     pgtype.Timestamptz
	Payload         []byte
	Quality         []byte
	TrackHint       *string
	CreatedAt       pgtype.Timestamptz
	HasPosition     bool
	Lat             float64
	Lng             float64
}

func (q *Queries) ListIncidentObservations(ctx context.Context, arg ListIncidentObservationsParams) ([]ListIncidentObservationsRow, error) {
	rows, err := q.db.Query(ctx, listIncidentObservations, arg.IncidentID, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIncidentObservationsRow{}
	for rows.Next() {
		var i ListIncidentObservationsRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.ObservationType,
			&i.ObservedAt,
			&i.ReceivedAt,
			&i.ProcessedAt,
			&i.Payload,
			&i.Quality,
			&i.TrackHint,
			&i.CreatedAt,
			&i.HasPosition,
			&i.Lat,
			&i.Lng,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncidentTracks = `-- name: ListIncidentTracks :many
SELECT
    t.id, t.external_ref, t.status, t.first_seen_at, t.last_seen_at,
    t.metadata, t.created_at, t.updated_at, t.closed_at,
    s.speed, s.heading, s.updated_at AS state_updated_at,
    (s.position IS NOT NULL)::boolean AS has_position,
    COALESCE(ST_Y(s.position::geometry), 0)::float8 AS lat,
    COALESCE(ST_X(s.position::geometry), 0)::float8 AS lng
FROM tracks t
JOIN incident_tracks it ON it.track_id = t.id
LEFT JOIN track_state s ON s.track_id = t.id
WHERE it.incident_id = $1
ORDER BY t.last_seen_at DESC
`

type ListIncidentTracksRow struct {
	ID             string
	ExternalRef    *string
	Status         string
	FirstSeenAt    pgtype.Timestamptz
	LastSeenAt     pgtype.Timestamptz
	Metadata       []byte
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	ClosedAt       pgtype.Timestamptz
	Speed          *float64
	Heading        *float64
	StateUpdatedAt pgtype.Timestamptz
	HasPosition    bool
	Lat            float64
	Lng            float64
}

func (q *Queries) ListIncidentTracks(ctx context.Context, incidentID string) ([]ListIncidentTracksRow, error) {
	rows, err := q.db.Query(ctx, listIncidentTracks, incidentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIncidentTracksRow{}
	for rows.Next() {
		var i ListIncidentTracksRow
		if err := rows.Scan(
			&i.ID,
			&i.ExternalRef,
			&i.Status,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClosedAt,
			&i.Speed,
			&i.Heading,
			&i.StateUpdatedAt,
			&i.HasPosition,
			&i.Lat,
			&i.Lng,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncidents = `-- name: ListIncidents :many
SELECT id, title, description, priority, status, assigned_operator, created_at, updated_at, resolved_at, closed_at FROM incidents
WHERE ($1::text IS NULL OR status = $1)
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type ListIncidentsParams struct {
	Status      *string
	OffsetCount int32
	LimitCount  int32
}

func (q *Queries) ListIncidents(ctx context.Context, arg ListIncidentsParams) ([]Incident, error) {
	rows, err := q.db.Query(ctx, listIncidents, arg.Status, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Incident{}
	for rows.Next() {
		var i Incident
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Priority,
			&i.Status,
			&i.AssignedOperator,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ResolvedAt,
			&i.ClosedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIncident = `-- name: UpdateIncident :one
UPDATE incidents
SET title = $1, description = $2, priority = $3,
    assigned_operator = $4, updated_at = now()
WHERE id = $5
RETURNING id, title, description, priority, status, assigned_operator, created_at, updated_at, resolved_at, closed_at
`

type UpdateIncidentParams struct {
	Title            string
	Description      string
	Priority         string
	AssignedOperator *string
	ID               string
}

func (q *Queries) UpdateIncident(ctx context.Context, arg UpdateIncidentParams) (Incident, error) {
	row := q.db.QueryRow(ctx, updateIncident,
		arg.Title,
		arg.Description,
		arg.Priority,
		arg.AssignedOperator,
		arg.ID,
	)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Priority,
		&i.Status,
		&i.AssignedOperator,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResolvedAt,
		&i.ClosedAt,
	)
	return i, err
}

const updateIncidentStatus = `-- name: UpdateIncidentStatus :one
UPDATE incidents
SET status = $1,
    updated_at = now(),
    resolved_at = CASE WHEN $1::text = 'RESOLVED' THEN now() ELSE resolved_at END,
    closed_at = CASE WHEN $1::text = 'CLOSED' THEN now() ELSE closed_at END
WHERE id = $2
RETURNING id, title, description, priority, status, assigned_operator, created_at, updated_at, resolved_at, closed_at
`

type UpdateIncidentStatusParams struct {
	Status string
	ID     string
}

func (q *Queries) UpdateIncidentStatus(ctx context.Context, arg UpdateIncidentStatusParams) (Incident, error) {
	row := q.db.QueryRow(ctx, updateIncidentStatus, arg.Status, arg.ID)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Priority,
		&i.Status,
		&i.AssignedOperator,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResolvedAt,
		&i.ClosedAt,
	)
	return i, err
}
