// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: missions.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignAssetToMission = `-- name: AssignAssetToMission :exec
INSERT INTO mission_assets (mission_id, asset_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AssignAssetToMissionParams struct {
	MissionID string
	AssetID   string
}

func (q *Queries) AssignAssetToMission(ctx context.Context, arg AssignAssetToMissionParams) error {
	_, err := q.db.Exec(ctx, assignAssetToMission, arg.MissionID, arg.AssetID)
	return err
}

const countMissions = `-- name: CountMissions :one
SELECT count(*) FROM missions
WHERE ($1::text IS NULL OR status = $1)
`

func (q *Queries) CountMissions(ctx context.Context, status *string) (int64, error) {
	row := q.db.QueryRow(ctx, countMissions, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMission = `-- name: CreateMission :one
INSERT INTO missions (
    id, name, objective, priority, status, incident_id, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, now(), now()
)
RETURNING id, name, objective, priority, status, incident_id, created_at, updated_at, started_at, ended_at
`

type CreateMissionParams struct {
	ID         string
	Name       string
	Objective  string
	Priority   string
	Status     string
	IncidentID *string
}

func (q *Queries) CreateMission(ctx context.Context, arg CreateMissionParams) (Mission, error) {
	row := q.db.QueryRow(ctx, createMission,
		arg.ID,
		arg.Name,
		arg.Objective,
		arg.Priority,
		arg.Status,
		arg.IncidentID,
	)
	var i Mission
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Objective,
		&i.Priority,
		&i.Status,
		&i.IncidentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const createMissionTask = `-- name: CreateMissionTask :one
INSERT INTO mission_tasks (id, mission_id, type, description, status, target_position)
VALUES (
    $1, $2, $3, $4, $5,
    CASE WHEN $6::boolean
         THEN ST_SetSRID(ST_MakePoint($7::float8, $8::float8), 4326)::geography
         ELSE NULL END
)
RETURNING id, mission_id, type, description, status, created_at, updated_at,
    (target_position IS NOT NULL)::boolean AS has_position,
    COALESCE(ST_Y(target_position::geometry), 0)::float8 AS lat,
    COALESCE(ST_X(target_position::geometry), 0)::float8 AS lng
`

type CreateMissionTaskParams struct {
	ID          string
	MissionID   string
	Type        string
	Description string
	Status      string
	HasTarget   bool
	Lng         float64
	Lat         float64
}

type CreateMissionTaskRow struct {
	ID          string
	MissionID   string
	Type        string
	Description string
	Status      string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	HasPosition bool
	Lat         float64
	Lng         float64
}

func (q *Queries) CreateMissionTask(ctx context.Context, arg CreateMissionTaskParams) (CreateMissionTaskRow, error) {
	row := q.db.QueryRow(ctx, createMissionTask,
		arg.ID,
		arg.MissionID,
		arg.Type,
		arg.Description,
		arg.Status,
		arg.HasTarget,
		arg.Lng,
		arg.Lat,
	)
	var i CreateMissionTaskRow
	err := row.Scan(
		&i.ID,
		&i.MissionID,
		&i.Type,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HasPosition,
		&i.Lat,
		&i.Lng,
	)
	return i, err
}

const getMission = `-- name: GetMission :one
SELECT id, name, objective, priority, status, incident_id, created_at, updated_at, started_at, ended_at FROM missions WHERE id = $1
`

func (q *Queries) GetMission(ctx context.Context, id string) (Mission, error) {
	row := q.db.QueryRow(ctx, getMission, id)
	var i Mission
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Objective,
		&i.Priority,
		&i.Status,
		&i.IncidentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const listMissionAssets = `-- name: ListMissionAssets :many
SELECT
    a.id, a.name, a.type, a.status, a.capabilities, a.created_at, a.updated_at,
    s.health, s.connection_state, s.last_seen_at, s.speed AS state_speed, s.heading AS state_heading,
    (s.position IS NOT NULL)::boolean AS has_position,
    COALESCE(ST_Y(s.position::geometry), 0)::float8 AS lat,
    COALESCE(ST_X(s.position::geometry), 0)::float8 AS lng
FROM assets a
JOIN mission_assets ma ON ma.asset_id = a.id
LEFT JOIN asset_state s ON s.asset_id = a.id
WHERE ma.mission_id = $1
ORDER BY a.name
`

type ListMissionAssetsRow struct {
	ID              string
	Name            string
	Type            string
	Status          string
	Capabilities    []byte
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	Health          *string
	ConnectionState *string
	LastSeenAt      pgtype.Timestamptz
	StateSpeed      *float64
	StateHeading    *float64
	HasPosition     bool
	Lat             float64
	Lng             float64
}

func (q *Queries) ListMissionAssets(ctx context.Context, missionID string) ([]ListMissionAssetsRow, error) {
	rows, err := q.db.Query(ctx, listMissionAssets, missionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMissionAssetsRow{}
	for rows.Next() {
		var i ListMissionAssetsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Status,
			&i.Capabilities,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Health,
			&i.ConnectionState,
			&i.LastSeenAt,
			&i.StateSpeed,
			&i.StateHeading,
			&i.HasPosition,
			&i.Lat,
			&i.Lng,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMissionTasks = `-- name: ListMissionTasks :many
SELECT
    id, mission_id, type, description, status, created_at, updated_at,
    (target_position IS NOT NULL)::boolean AS has_position,
    COALESCE(ST_Y(target_position::geometry), 0)::float8 AS lat,
    COALESCE(ST_X(target_position::geometry), 0)::float8 AS lng
FROM mission_tasks
WHERE mission_id = $1
ORDER BY created_at ASC
`

type ListMissionTasksRow struct {
	ID          string
	MissionID   string
	Type        string
	Description string
	Status      string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	HasPosition bool
	Lat         float64
	Lng         float64
}

func (q *Queries) ListMissionTasks(ctx context.Context, missionID string) ([]ListMissionTasksRow, error) {
	rows, err := q.db.Query(ctx, listMissionTasks, missionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMissionTasksRow{}
	for rows.Next() {
		var i ListMissionTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.MissionID,
			&i.Type,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.HasPosition,
			&i.Lat,
			&i.Lng,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMissions = `-- name: ListMissions :many
SELECT id, name, objective, priority, status, incident_id, created_at, updated_at, started_at, ended_at FROM missions
WHERE ($1::text IS NULL OR status = $1)
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type ListMissionsParams struct {
	Status      *string
	OffsetCount int32
	LimitCount  int32
}

func (q *Queries) ListMissions(ctx context.Context, arg ListMissionsParams) ([]Mission, error) {
	rows, err := q.db.Query(ctx, listMissions, arg.Status, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Mission{}
	for rows.Next() {
		var i Mission
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Objective,
			&i.Priority,
			&i.Status,
			&i.IncidentID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartedAt,
			&i.EndedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMissionsForAsset = `-- name: ListMissionsForAsset :many
SELECT m.id, m.name, m.objective, m.priority, m.status, m.incident_id, m.created_at, m.updated_at, m.started_at, m.ended_at FROM missions m
JOIN mission_assets ma ON ma.mission_id = m.id
WHERE ma.asset_id = $1
ORDER BY m.created_at DESC
`

func (q *Queries) ListMissionsForAsset(ctx context.Context, assetID string) ([]Mission, error) {
	rows, err := q.db.Query(ctx, listMissionsForAsset, assetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Mission{}
	for rows.Next() {
		var i Mission
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Objective,
			&i.Priority,
			&i.Status,
			&i.IncidentID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartedAt,
			&i.EndedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMissionStatus = `-- name: UpdateMissionStatus :one
UPDATE missions
SET status = $1,
    updated_at = now(),
    started_at = CASE WHEN $1::text = 'ACTIVE' AND started_at IS NULL THEN now() ELSE started_at END,
    ended_at = CASE WHEN $1::text IN ('COMPLETED', 'ABORTED') THEN now() ELSE ended_at END
WHERE id = $2
  AND status = $3
RETURNING id, name, objective, priority, status, incident_id, created_at, updated_at, started_at, ended_at
`

type UpdateMissionStatusParams struct {
	Status         string
	ID             string
	ExpectedStatus string
}

func (q *Queries) UpdateMissionStatus(ctx context.Context, arg UpdateMissionStatusParams) (Mission, error) {
	row := q.db.QueryRow(ctx, updateMissionStatus, arg.Status, arg.ID, arg.ExpectedStatus)
	var i Mission
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Objective,
		&i.Priority,
		&i.Status,
		&i.IncidentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const updateMissionTaskStatus = `-- name: UpdateMissionTaskStatus :one
UPDATE mission_tasks
SET status = $1, updated_at = now()
WHERE id = $2
  AND mission_id = $3
RETURNING id, mission_id, type, description, status, created_at, updated_at,
    (target_position IS NOT NULL)::boolean AS has_position,
    COALESCE(ST_Y(target_position::geometry), 0)::float8 AS lat,
    COALESCE(ST_X(target_position::geometry), 0)::float8 AS lng
`

type UpdateMissionTaskStatusParams struct {
	Status    string
	ID        string
	MissionID string
}

type UpdateMissionTaskStatusRow struct {
	ID          string
	MissionID   string
	Type        string
	Description string
	Status      string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	HasPosition bool
	Lat         float64
	Lng         float64
}

func (q *Queries) UpdateMissionTaskStatus(ctx context.Context, arg UpdateMissionTaskStatusParams) (UpdateMissionTaskStatusRow, error) {
	row := q.db.QueryRow(ctx, updateMissionTaskStatus, arg.Status, arg.ID, arg.MissionID)
	var i UpdateMissionTaskStatusRow
	err := row.Scan(
		&i.ID,
		&i.MissionID,
		&i.Type,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HasPosition,
		&i.Lat,
		&i.Lng,
	)
	return i, err
}
