// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Alert struct {
	ID              string
	Type            string
	Severity        string
	State           string
	Title           string
	Message         *string
	SourceReference []byte
	TrackID         *string
	AssetID         *string
	GeofenceID      *string
	IncidentID      *string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	AcknowledgedAt  pgtype.Timestamptz
	AcknowledgedBy  *string
	ResolvedAt      pgtype.Timestamptz
	ResolvedBy      *string
}

type Assessment struct {
	ID          string
	SubjectType string
	SubjectID   string
	Type        string
	Conclusion  string
	Confidence  *float64
	Method      string
	CreatedBy   *string
	CreatedAt   pgtype.Timestamptz
}

type AssessmentEvidence struct {
	AssessmentID string
	EvidenceType string
	EvidenceID   string
	AddedAt      pgtype.Timestamptz
}

type Asset struct {
	ID           string
	Name         string
	Type         string
	Status       string
	Capabilities []byte
	Metadata     []byte
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type AssetState struct {
	AssetID         string
	Position        interface{}
	Speed           *float64
	Heading         *float64
	Health          *string
	ConnectionState string
	LastSeenAt      pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type AssetTelemetry struct {
	ID              string
	MessageID       *string
	AssetID         string
	SourceID        *string
	ObservedAt      pgtype.Timestamptz
	ReceivedAt      pgtype.Timestamptz
	Position        interface{}
	Speed           *float64
	Heading         *float64
	Health          *string
	ConnectionState *string
	Payload         []byte
	CreatedAt       pgtype.Timestamptz
}

type AuditEvent struct {
	ID            string
	OccurredAt    pgtype.Timestamptz
	ActorType     string
	ActorID       *string
	Action        string
	SubjectType   *string
	SubjectID     *string
	CorrelationID *string
	Data          []byte
	CreatedAt     pgtype.Timestamptz
}

type Classification struct {
	ID              string
	TrackID         string
	Label           string
	Confidence      *float64
	Method          string
	SourceReference *string
	CreatedBy       *string
	CreatedAt       pgtype.Timestamptz
}

type Command struct {
	ID             string
	AssetID        string
	MissionID      *string
	IncidentID     *string
	Type           string
	Payload        []byte
	State          string
	CreatedBy      *string
	CorrelationID  *string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	QueuedAt       pgtype.Timestamptz
	SentAt         pgtype.Timestamptz
	AcknowledgedAt pgtype.Timestamptz
	CompletedAt    pgtype.Timestamptz
	FailureReason  *string
}

type Geofence struct {
	ID        string
	Name      string
	Type      string
	Geometry  interface{}
	Severity  string
	Active    bool
	Metadata  []byte
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type GeofenceState struct {
	GeofenceID string
	TrackID    string
	Inside     bool
	Since      pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type Incident struct {
	ID               string
	Title            string
	Description      string
	Priority         string
	Status           string
	AssignedOperator *string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	ResolvedAt       pgtype.Timestamptz
	ClosedAt         pgtype.Timestamptz
}

type IncidentAlert struct {
	IncidentID string
	AlertID    string
	AddedAt    pgtype.Timestamptz
}

type IncidentAssessment struct {
	IncidentID   string
	AssessmentID string
	AddedAt      pgtype.Timestamptz
}

type IncidentAsset struct {
	IncidentID string
	AssetID    string
	AddedAt    pgtype.Timestamptz
}

type IncidentObservation struct {
	IncidentID    string
	ObservationID string
	AddedAt       pgtype.Timestamptz
}

type IncidentTrack struct {
	IncidentID string
	TrackID    string
	AddedAt    pgtype.Timestamptz
}

type Mission struct {
	ID         string
	Name       string
	Objective  string
	Priority   string
	Status     string
	IncidentID *string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	StartedAt  pgtype.Timestamptz
	EndedAt    pgtype.Timestamptz
}

type MissionAsset struct {
	MissionID  string
	AssetID    string
	AssignedAt pgtype.Timestamptz
}

type MissionTask struct {
	ID             string
	MissionID      string
	Type           string
	Description    string
	Status         string
	TargetPosition interface{}
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type Observation struct {
	ID              string
	SourceID        string
	ObservationType string
	ObservedAt      pgtype.Timestamptz
	ReceivedAt      pgtype.Timestamptz
	ProcessedAt     pgtype.Timestamptz
	Position        interface{}
	Payload         []byte
	Quality         []byte
	TrackHint       *string
	CreatedAt       pgtype.Timestamptz
}

type Operator struct {
	ID        string
	Name      string
	Role      string
	CreatedAt pgtype.Timestamptz
}

type ScenarioRun struct {
	ID            string
	ScenarioName  string
	Seed          int64
	Status        string
	PlaybackSpeed float64
	VirtualTimeMs int64
	StartedAt     pgtype.Timestamptz
	EndedAt       pgtype.Timestamptz
	Error         *string
	CreatedAt     pgtype.Timestamptz
}

type Source struct {
	ID        string
	Name      string
	Type      string
	Status    string
	Metadata  []byte
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Track struct {
	ID          string
	ExternalRef *string
	Status      string
	FirstSeenAt pgtype.Timestamptz
	LastSeenAt  pgtype.Timestamptz
	Metadata    []byte
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	ClosedAt    pgtype.Timestamptz
}

type TrackHistory struct {
	ID         string
	TrackID    string
	ObservedAt pgtype.Timestamptz
	Position   interface{}
	Speed      *float64
	Heading    *float64
	CreatedAt  pgtype.Timestamptz
}

type TrackObservation struct {
	TrackID       string
	ObservationID string
	SourceID      string
	ObservedAt    pgtype.Timestamptz
	Position      interface{}
	CreatedAt     pgtype.Timestamptz
}

type TrackState struct {
	TrackID   string
	Position  interface{}
	Speed     *float64
	Heading   *float64
	UpdatedAt pgtype.Timestamptz
}
