// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: observations.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countObservations = `-- name: CountObservations :one
SELECT count(*) FROM observations
`

func (q *Queries) CountObservations(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countObservations)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countObservationsByTrack = `-- name: CountObservationsByTrack :one
SELECT count(*)
FROM track_observations
WHERE track_id = $1
`

func (q *Queries) CountObservationsByTrack(ctx context.Context, trackID string) (int64, error) {
	row := q.db.QueryRow(ctx, countObservationsByTrack, trackID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createObservation = `-- name: CreateObservation :one
INSERT INTO observations (
    id, source_id, observation_type, observed_at, received_at, processed_at,
    position, payload, quality, track_hint
) VALUES (
    $1, $2, $3, $4, $5, $6,
    CASE WHEN $7::boolean
         THEN ST_SetSRID(ST_MakePoint($8::float8, $9::float8), 4326)::geography
         ELSE NULL END,
    $10, $11, $12
)
RETURNING
    id, source_id, observation_type, observed_at, received_at, processed_at,
    payload, quality, track_hint, created_at,
    (position IS NOT NULL)::boolean AS has_position,
    COALESCE(ST_Y(position::geometry), 0)::float8 AS lat,
    COALESCE(ST_X(position::geometry), 0)::float8 AS lng
`

type CreateObservationParams struct {
	ID              string
	SourceID        string
	ObservationType string
	ObservedAt      pgtype.Timestamptz
	ReceivedAt      pgtype.Timestamptz
	ProcessedAt     pgtype.Timestamptz
	HasPosition     bool
	Lng             float64
	Lat             float64
	Payload         []byte
	Quality         []byte
	TrackHint       *string
}

type CreateObservationRow struct {
	ID              string
	SourceID        string
	ObservationType string
	ObservedAt      pgtype.Timestamptz
	ReceivedAt      pgtype.Timestamptz
	ProcessedAt     pgtype.Timestamptz
	Payload         []byte
	Quality         []byte
	TrackHint       *string
	CreatedAt       pgtype.Timestamptz
	HasPosition     bool
	Lat             float64
	Lng             float64
}

func (q *Queries) CreateObservation(ctx context.Context, arg CreateObservationParams) (CreateObservationRow, error) {
	row := q.db.QueryRow(ctx, createObservation,
		arg.ID,
		arg.SourceID,
		arg.ObservationType,
		arg.ObservedAt,
		arg.ReceivedAt,
		arg.ProcessedAt,
		arg.HasPosition,
		arg.Lng,
		arg.Lat,
		arg.Payload,
		arg.Quality,
		arg.TrackHint,
	)
	var i CreateObservationRow
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.ObservationType,
		&i.ObservedAt,
		&i.ReceivedAt,
		&i.ProcessedAt,
		&i.Payload,
		&i.Quality,
		&i.TrackHint,
		&i.CreatedAt,
		&i.HasPosition,
		&i.Lat,
		&i.Lng,
	)
	return i, err
}

const getObservation = `-- name: GetObservation :one
SELECT
    id, source_id, observation_type, observed_at, received_at, processed_at,
    payload, quality, track_hint, created_at,
    (position IS NOT NULL)::boolean AS has_position,
    COALESCE(ST_Y(position::geometry), 0)::float8 AS lat,
    COALESCE(ST_X(position::geometry), 0)::float8 AS lng
FROM observations
WHERE id = $1
`

type GetObservationRow struct {
	ID              string
	SourceID        string
	ObservationType string
	ObservedAt      pgtype.Timestamptz
	ReceivedAt      pgtype.Timestamptz
	ProcessedAt     pgtype.Timestamptz
	Payload         []byte
	Quality         []byte
	TrackHint       *string
	CreatedAt       pgtype.Timestamptz
	HasPosition     bool
	Lat             float64
	Lng             float64
}

func (q *Queries) GetObservation(ctx context.Context, id string) (GetObservationRow, error) {
	row := q.db.QueryRow(ctx, getObservation, id)
	var i GetObservationRow
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.ObservationType,
		&i.ObservedAt,
		&i.ReceivedAt,
		&i.ProcessedAt,
		&i.Payload,
		&i.Quality,
		&i.TrackHint,
		&i.CreatedAt,
		&i.HasPosition,
		&i.Lat,
		&i.Lng,
	)
	return i, err
}

const listObservations = `-- name: ListObservations :many
SELECT
    id, source_id, observation_type, observed_at, received_at, processed_at,
    payload, quality, track_hint, created_at,
    (position IS NOT NULL)::boolean AS has_position,
    COALESCE(ST_Y(position::geometry), 0)::float8 AS lat,
    COALESCE(ST_X(position::geometry), 0)::float8 AS lng
FROM observations
ORDER BY observed_at DESC, id DESC
LIMIT $2 OFFSET $1
`

type ListObservationsParams struct {
	OffsetCount int32
	LimitCount  int32
}

type ListObservationsRow struct {
	ID              string
	SourceID        string
	ObservationType string
	ObservedAt      pgtype.Timestamptz
	ReceivedAt      pgtype.Timestamptz
	ProcessedAt     pgtype.Timestamptz
	Payload         []byte
	Quality         []byte
	TrackHint       *string
	CreatedAt       pgtype.Timestamptz
	HasPosition     bool
	Lat             float64
	Lng             float64
}

func (q *Queries) ListObservations(ctx context.Context, arg ListObservationsParams) ([]ListObservationsRow, error) {
	rows, err := q.db.Query(ctx, listObservations, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListObservationsRow{}
	for rows.Next() {
		var i ListObservationsRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.ObservationType,
			&i.ObservedAt,
			&i.ReceivedAt,
			&i.ProcessedAt,
			&i.Payload,
			&i.Quality,
			&i.TrackHint,
			&i.CreatedAt,
			&i.HasPosition,
			&i.Lat,
			&i.Lng,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listObservationsByTrack = `-- name: ListObservationsByTrack :many
SELECT
    o.id, o.source_id, o.observation_type, o.observed_at, o.received_at, o.processed_at,
    o.payload, o.quality, o.track_hint, o.created_at,
    (o.position IS NOT NULL)::boolean AS has_position,
    COALESCE(ST_Y(o.position::geometry), 0)::float8 AS lat,
    COALESCE(ST_X(o.position::geometry), 0)::float8 AS lng
FROM observations o
JOIN track_observations t ON t.observation_id = o.id
WHERE t.track_id = $1
ORDER BY o.observed_at DESC, o.id DESC
LIMIT $3 OFFSET $2
`

type ListObservationsByTrackParams struct {
	TrackID     string
	OffsetCount int32
	LimitCount  int32
}

type ListObservationsByTrackRow struct {
	ID              string
	SourceID        string
	ObservationType string
	ObservedAt      pgtype.Timestamptz
	ReceivedAt      pgtype.Timestamptz
	ProcessedAt     pgtype.Timestamptz
	Payload         []byte
	Quality         []byte
	TrackHint       *string
	CreatedAt       pgtype.Timestamptz
	HasPosition     bool
	Lat             float64
	Lng             float64
}

func (q *Queries) ListObservationsByTrack(ctx context.Context, arg ListObservationsByTrackParams) ([]ListObservationsByTrackRow, error) {
	rows, err := q.db.Query(ctx, listObservationsByTrack, arg.TrackID, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListObservationsByTrackRow{}
	for rows.Next() {
		var i ListObservationsByTrackRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.ObservationType,
			&i.ObservedAt,
			&i.ReceivedAt,
			&i.ProcessedAt,
			&i.Payload,
			&i.Quality,
			&i.TrackHint,
			&i.CreatedAt,
			&i.HasPosition,
			&i.Lat,
			&i.Lng,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markObservationProcessed = `-- name: MarkObservationProcessed :exec
UPDATE observations SET processed_at = now() WHERE id = $1
`

func (q *Queries) MarkObservationProcessed(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, markObservationProcessed, id)
	return err
}
