// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scenario_runs.sql

package dbgen

import (
	"context"
)

const countScenarioRuns = `-- name: CountScenarioRuns :one
SELECT count(*)::bigint FROM scenario_runs
`

func (q *Queries) CountScenarioRuns(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countScenarioRuns)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createScenarioRun = `-- name: CreateScenarioRun :one
INSERT INTO scenario_runs (
    id, scenario_name, seed, status, playback_speed, virtual_time_ms, started_at, created_at
) VALUES (
    $1, $2, $3, $4, $5, 0, now(), now()
)
RETURNING id, scenario_name, seed, status, playback_speed, virtual_time_ms, started_at, ended_at, error, created_at, last_action, last_action_at_ms, action_error
`

type CreateScenarioRunParams struct {
	ID            string
	ScenarioName  string
	Seed          int64
	Status        string
	PlaybackSpeed float64
}

func (q *Queries) CreateScenarioRun(ctx context.Context, arg CreateScenarioRunParams) (ScenarioRun, error) {
	row := q.db.QueryRow(ctx, createScenarioRun,
		arg.ID,
		arg.ScenarioName,
		arg.Seed,
		arg.Status,
		arg.PlaybackSpeed,
	)
	var i ScenarioRun
	err := row.Scan(
		&i.ID,
		&i.ScenarioName,
		&i.Seed,
		&i.Status,
		&i.PlaybackSpeed,
		&i.VirtualTimeMs,
		&i.StartedAt,
		&i.EndedAt,
		&i.Error,
		&i.CreatedAt,
		&i.LastAction,
		&i.LastActionAtMs,
		&i.ActionError,
	)
	return i, err
}

const getScenarioRun = `-- name: GetScenarioRun :one
SELECT id, scenario_name, seed, status, playback_speed, virtual_time_ms, started_at, ended_at, error, created_at, last_action, last_action_at_ms, action_error FROM scenario_runs WHERE id = $1
`

func (q *Queries) GetScenarioRun(ctx context.Context, id string) (ScenarioRun, error) {
	row := q.db.QueryRow(ctx, getScenarioRun, id)
	var i ScenarioRun
	err := row.Scan(
		&i.ID,
		&i.ScenarioName,
		&i.Seed,
		&i.Status,
		&i.PlaybackSpeed,
		&i.VirtualTimeMs,
		&i.StartedAt,
		&i.EndedAt,
		&i.Error,
		&i.CreatedAt,
		&i.LastAction,
		&i.LastActionAtMs,
		&i.ActionError,
	)
	return i, err
}

const listActiveScenarioRuns = `-- name: ListActiveScenarioRuns :many
SELECT id, scenario_name, seed, status, playback_speed, virtual_time_ms, started_at, ended_at, error, created_at, last_action, last_action_at_ms, action_error FROM scenario_runs WHERE status IN ('RUNNING', 'PAUSED') ORDER BY started_at DESC
`

func (q *Queries) ListActiveScenarioRuns(ctx context.Context) ([]ScenarioRun, error) {
	rows, err := q.db.Query(ctx, listActiveScenarioRuns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScenarioRun{}
	for rows.Next() {
		var i ScenarioRun
		if err := rows.Scan(
			&i.ID,
			&i.ScenarioName,
			&i.Seed,
			&i.Status,
			&i.PlaybackSpeed,
			&i.VirtualTimeMs,
			&i.StartedAt,
			&i.EndedAt,
			&i.Error,
			&i.CreatedAt,
			&i.LastAction,
			&i.LastActionAtMs,
			&i.ActionError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScenarioRuns = `-- name: ListScenarioRuns :many
SELECT id, scenario_name, seed, status, playback_speed, virtual_time_ms, started_at, ended_at, error, created_at, last_action, last_action_at_ms, action_error FROM scenario_runs
ORDER BY started_at DESC
LIMIT $2 OFFSET $1
`

type ListScenarioRunsParams struct {
	OffsetCount int32
	LimitCount  int32
}

func (q *Queries) ListScenarioRuns(ctx context.Context, arg ListScenarioRunsParams) ([]ScenarioRun, error) {
	rows, err := q.db.Query(ctx, listScenarioRuns, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScenarioRun{}
	for rows.Next() {
		var i ScenarioRun
		if err := rows.Scan(
			&i.ID,
			&i.ScenarioName,
			&i.Seed,
			&i.Status,
			&i.PlaybackSpeed,
			&i.VirtualTimeMs,
			&i.StartedAt,
			&i.EndedAt,
			&i.Error,
			&i.CreatedAt,
			&i.LastAction,
			&i.LastActionAtMs,
			&i.ActionError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateScenarioRunProgress = `-- name: UpdateScenarioRunProgress :exec
UPDATE scenario_runs
SET virtual_time_ms = $1
WHERE id = $2
`

type UpdateScenarioRunProgressParams struct {
	VirtualTimeMs int64
	ID            string
}

func (q *Queries) UpdateScenarioRunProgress(ctx context.Context, arg UpdateScenarioRunProgressParams) error {
	_, err := q.db.Exec(ctx, updateScenarioRunProgress, arg.VirtualTimeMs, arg.ID)
	return err
}

const updateScenarioRunSpeed = `-- name: UpdateScenarioRunSpeed :one
UPDATE scenario_runs
SET playback_speed = $1
WHERE id = $2
RETURNING id, scenario_name, seed, status, playback_speed, virtual_time_ms, started_at, ended_at, error, created_at, last_action, last_action_at_ms, action_error
`

type UpdateScenarioRunSpeedParams struct {
	PlaybackSpeed float64
	ID            string
}

func (q *Queries) UpdateScenarioRunSpeed(ctx context.Context, arg UpdateScenarioRunSpeedParams) (ScenarioRun, error) {
	row := q.db.QueryRow(ctx, updateScenarioRunSpeed, arg.PlaybackSpeed, arg.ID)
	var i ScenarioRun
	err := row.Scan(
		&i.ID,
		&i.ScenarioName,
		&i.Seed,
		&i.Status,
		&i.PlaybackSpeed,
		&i.VirtualTimeMs,
		&i.StartedAt,
		&i.EndedAt,
		&i.Error,
		&i.CreatedAt,
		&i.LastAction,
		&i.LastActionAtMs,
		&i.ActionError,
	)
	return i, err
}

const updateScenarioRunStatus = `-- name: UpdateScenarioRunStatus :one
UPDATE scenario_runs
SET status = $1,
    error = $2,
    ended_at = CASE WHEN $1 IN ('COMPLETED', 'STOPPED', 'FAILED') THEN now() ELSE ended_at END
WHERE id = $3
RETURNING id, scenario_name, seed, status, playback_speed, virtual_time_ms, started_at, ended_at, error, created_at, last_action, last_action_at_ms, action_error
`

type UpdateScenarioRunStatusParams struct {
	Status string
	Error  *string
	ID     string
}

func (q *Queries) UpdateScenarioRunStatus(ctx context.Context, arg UpdateScenarioRunStatusParams) (ScenarioRun, error) {
	row := q.db.QueryRow(ctx, updateScenarioRunStatus, arg.Status, arg.Error, arg.ID)
	var i ScenarioRun
	err := row.Scan(
		&i.ID,
		&i.ScenarioName,
		&i.Seed,
		&i.Status,
		&i.PlaybackSpeed,
		&i.VirtualTimeMs,
		&i.StartedAt,
		&i.EndedAt,
		&i.Error,
		&i.CreatedAt,
		&i.LastAction,
		&i.LastActionAtMs,
		&i.ActionError,
	)
	return i, err
}
