// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scenario_run_events.sql

package dbgen

import (
	"context"
)

const createScenarioRunEvent = `-- name: CreateScenarioRunEvent :exec
INSERT INTO scenario_run_events (
    run_id, sequence, virtual_time_ms, action_name, status, error, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, now(), now()
)
ON CONFLICT (run_id, sequence) DO UPDATE SET
    virtual_time_ms = EXCLUDED.virtual_time_ms,
    action_name = EXCLUDED.action_name,
    status = EXCLUDED.status,
    error = EXCLUDED.error,
    updated_at = now()
`

type CreateScenarioRunEventParams struct {
	RunID         string
	Sequence      int32
	VirtualTimeMs int64
	ActionName    string
	Status        string
	Error         *string
}

func (q *Queries) CreateScenarioRunEvent(ctx context.Context, arg CreateScenarioRunEventParams) error {
	_, err := q.db.Exec(ctx, createScenarioRunEvent,
		arg.RunID,
		arg.Sequence,
		arg.VirtualTimeMs,
		arg.ActionName,
		arg.Status,
		arg.Error,
	)
	return err
}

const listScenarioRunEvents = `-- name: ListScenarioRunEvents :many
SELECT run_id, sequence, virtual_time_ms, action_name, status, error, created_at, updated_at
FROM scenario_run_events
WHERE run_id = $1
ORDER BY virtual_time_ms, sequence
`

func (q *Queries) ListScenarioRunEvents(ctx context.Context, runID string) ([]ScenarioRunEvent, error) {
	rows, err := q.db.Query(ctx, listScenarioRunEvents, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScenarioRunEvent{}
	for rows.Next() {
		var i ScenarioRunEvent
		if err := rows.Scan(
			&i.RunID,
			&i.Sequence,
			&i.VirtualTimeMs,
			&i.ActionName,
			&i.Status,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const skipPendingScenarioRunEvents = `-- name: SkipPendingScenarioRunEvents :exec
UPDATE scenario_run_events
SET status = 'skipped',
    error = COALESCE(NULLIF($1, ''), error),
    updated_at = now()
WHERE run_id = $2 AND status IN ('pending', 'running')
`

type SkipPendingScenarioRunEventsParams struct {
	Error interface{}
	RunID string
}

func (q *Queries) SkipPendingScenarioRunEvents(ctx context.Context, arg SkipPendingScenarioRunEventsParams) error {
	_, err := q.db.Exec(ctx, skipPendingScenarioRunEvents, arg.Error, arg.RunID)
	return err
}

const updateScenarioRunCursor = `-- name: UpdateScenarioRunCursor :one
UPDATE scenario_runs
SET virtual_time_ms = $1,
    last_action = $2,
    last_action_at_ms = $3,
    action_error = $4
WHERE id = $5
RETURNING id, scenario_name, seed, status, playback_speed, virtual_time_ms, started_at, ended_at, error, created_at, last_action, last_action_at_ms, action_error
`

type UpdateScenarioRunCursorParams struct {
	VirtualTimeMs  int64
	LastAction     *string
	LastActionAtMs int64
	ActionError    *string
	ID             string
}

func (q *Queries) UpdateScenarioRunCursor(ctx context.Context, arg UpdateScenarioRunCursorParams) (ScenarioRun, error) {
	row := q.db.QueryRow(ctx, updateScenarioRunCursor,
		arg.VirtualTimeMs,
		arg.LastAction,
		arg.LastActionAtMs,
		arg.ActionError,
		arg.ID,
	)
	var i ScenarioRun
	err := row.Scan(
		&i.ID,
		&i.ScenarioName,
		&i.Seed,
		&i.Status,
		&i.PlaybackSpeed,
		&i.VirtualTimeMs,
		&i.StartedAt,
		&i.EndedAt,
		&i.Error,
		&i.CreatedAt,
		&i.LastAction,
		&i.LastActionAtMs,
		&i.ActionError,
	)
	return i, err
}

const updateScenarioRunEvent = `-- name: UpdateScenarioRunEvent :exec
UPDATE scenario_run_events
SET status = $1,
    error = $2,
    updated_at = now()
WHERE run_id = $3 AND sequence = $4
`

type UpdateScenarioRunEventParams struct {
	Status   string
	Error    *string
	RunID    string
	Sequence int32
}

func (q *Queries) UpdateScenarioRunEvent(ctx context.Context, arg UpdateScenarioRunEventParams) error {
	_, err := q.db.Exec(ctx, updateScenarioRunEvent,
		arg.Status,
		arg.Error,
		arg.RunID,
		arg.Sequence,
	)
	return err
}
