// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sources.sql

package dbgen

import (
	"context"
)

const countSources = `-- name: CountSources :one
SELECT count(*) FROM sources
`

func (q *Queries) CountSources(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSources)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSource = `-- name: CreateSource :one
INSERT INTO sources (id, name, type, status, metadata, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, now(), now())
RETURNING id, name, type, status, metadata, created_at, updated_at
`

type CreateSourceParams struct {
	ID       string
	Name     string
	Type     string
	Status   string
	Metadata []byte
}

func (q *Queries) CreateSource(ctx context.Context, arg CreateSourceParams) (Source, error) {
	row := q.db.QueryRow(ctx, createSource,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.Status,
		arg.Metadata,
	)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSource = `-- name: GetSource :one
SELECT id, name, type, status, metadata, created_at, updated_at FROM sources WHERE id = $1
`

func (q *Queries) GetSource(ctx context.Context, id string) (Source, error) {
	row := q.db.QueryRow(ctx, getSource, id)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSources = `-- name: ListSources :many
SELECT id, name, type, status, metadata, created_at, updated_at FROM sources
ORDER BY created_at DESC
LIMIT $2 OFFSET $1
`

type ListSourcesParams struct {
	OffsetCount int32
	LimitCount  int32
}

func (q *Queries) ListSources(ctx context.Context, arg ListSourcesParams) ([]Source, error) {
	rows, err := q.db.Query(ctx, listSources, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Source{}
	for rows.Next() {
		var i Source
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Status,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sourceExists = `-- name: SourceExists :one
SELECT EXISTS (SELECT 1 FROM sources WHERE id = $1)
`

func (q *Queries) SourceExists(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRow(ctx, sourceExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateSourceStatus = `-- name: UpdateSourceStatus :one
UPDATE sources
SET status = $1, updated_at = now()
WHERE id = $2
RETURNING id, name, type, status, metadata, created_at, updated_at
`

type UpdateSourceStatusParams struct {
	Status string
	ID     string
}

func (q *Queries) UpdateSourceStatus(ctx context.Context, arg UpdateSourceStatusParams) (Source, error) {
	row := q.db.QueryRow(ctx, updateSourceStatus, arg.Status, arg.ID)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
