// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: telemetry.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countTelemetryByAsset = `-- name: CountTelemetryByAsset :one
SELECT count(*) FROM asset_telemetry WHERE asset_id = $1
`

func (q *Queries) CountTelemetryByAsset(ctx context.Context, assetID string) (int64, error) {
	row := q.db.QueryRow(ctx, countTelemetryByAsset, assetID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTelemetry = `-- name: CreateTelemetry :one
INSERT INTO asset_telemetry (
    id, message_id, asset_id, source_id, observed_at, received_at,
    position, speed, heading, health, connection_state, payload
) VALUES (
    $1, $2, $3, $4, $5, $6,
    CASE WHEN $7::boolean
         THEN ST_SetSRID(ST_MakePoint($8::float8, $9::float8), 4326)::geography
         ELSE NULL END,
    $10, $11, $12, $13, $14
)
ON CONFLICT (message_id) WHERE message_id IS NOT NULL DO NOTHING
RETURNING id
`

type CreateTelemetryParams struct {
	ID              string
	MessageID       *string
	AssetID         string
	SourceID        *string
	ObservedAt      pgtype.Timestamptz
	ReceivedAt      pgtype.Timestamptz
	HasPosition     bool
	Lng             float64
	Lat             float64
	Speed           *float64
	Heading         *float64
	Health          *string
	ConnectionState *string
	Payload         []byte
}

func (q *Queries) CreateTelemetry(ctx context.Context, arg CreateTelemetryParams) (string, error) {
	row := q.db.QueryRow(ctx, createTelemetry,
		arg.ID,
		arg.MessageID,
		arg.AssetID,
		arg.SourceID,
		arg.ObservedAt,
		arg.ReceivedAt,
		arg.HasPosition,
		arg.Lng,
		arg.Lat,
		arg.Speed,
		arg.Heading,
		arg.Health,
		arg.ConnectionState,
		arg.Payload,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const latestTelemetryForAsset = `-- name: LatestTelemetryForAsset :one
SELECT
    id, message_id, asset_id, source_id, observed_at, received_at,
    speed, heading, health, connection_state, payload, created_at,
    (position IS NOT NULL)::boolean AS has_position,
    COALESCE(ST_Y(position::geometry), 0)::float8 AS lat,
    COALESCE(ST_X(position::geometry), 0)::float8 AS lng
FROM asset_telemetry
WHERE asset_id = $1
ORDER BY observed_at DESC, id DESC
LIMIT 1
`

type LatestTelemetryForAssetRow struct {
	ID              string
	MessageID       *string
	AssetID         string
	SourceID        *string
	ObservedAt      pgtype.Timestamptz
	ReceivedAt      pgtype.Timestamptz
	Speed           *float64
	Heading         *float64
	Health          *string
	ConnectionState *string
	Payload         []byte
	CreatedAt       pgtype.Timestamptz
	HasPosition     bool
	Lat             float64
	Lng             float64
}

func (q *Queries) LatestTelemetryForAsset(ctx context.Context, assetID string) (LatestTelemetryForAssetRow, error) {
	row := q.db.QueryRow(ctx, latestTelemetryForAsset, assetID)
	var i LatestTelemetryForAssetRow
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.AssetID,
		&i.SourceID,
		&i.ObservedAt,
		&i.ReceivedAt,
		&i.Speed,
		&i.Heading,
		&i.Health,
		&i.ConnectionState,
		&i.Payload,
		&i.CreatedAt,
		&i.HasPosition,
		&i.Lat,
		&i.Lng,
	)
	return i, err
}

const listTelemetryByAsset = `-- name: ListTelemetryByAsset :many
SELECT
    id, message_id, asset_id, source_id, observed_at, received_at,
    speed, heading, health, connection_state, payload, created_at,
    (position IS NOT NULL)::boolean AS has_position,
    COALESCE(ST_Y(position::geometry), 0)::float8 AS lat,
    COALESCE(ST_X(position::geometry), 0)::float8 AS lng
FROM asset_telemetry
WHERE asset_id = $1
ORDER BY observed_at DESC, id DESC
LIMIT $3 OFFSET $2
`

type ListTelemetryByAssetParams struct {
	AssetID     string
	OffsetCount int32
	LimitCount  int32
}

type ListTelemetryByAssetRow struct {
	ID              string
	MessageID       *string
	AssetID         string
	SourceID        *string
	ObservedAt      pgtype.Timestamptz
	ReceivedAt      pgtype.Timestamptz
	Speed           *float64
	Heading         *float64
	Health          *string
	ConnectionState *string
	Payload         []byte
	CreatedAt       pgtype.Timestamptz
	HasPosition     bool
	Lat             float64
	Lng             float64
}

func (q *Queries) ListTelemetryByAsset(ctx context.Context, arg ListTelemetryByAssetParams) ([]ListTelemetryByAssetRow, error) {
	rows, err := q.db.Query(ctx, listTelemetryByAsset, arg.AssetID, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTelemetryByAssetRow{}
	for rows.Next() {
		var i ListTelemetryByAssetRow
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.AssetID,
			&i.SourceID,
			&i.ObservedAt,
			&i.ReceivedAt,
			&i.Speed,
			&i.Heading,
			&i.Health,
			&i.ConnectionState,
			&i.Payload,
			&i.CreatedAt,
			&i.HasPosition,
			&i.Lat,
			&i.Lng,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
