// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tracks.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const attachObservationToTrack = `-- name: AttachObservationToTrack :execrows
INSERT INTO track_observations (track_id, observation_id, source_id, observed_at, position)
SELECT $1, o.id, o.source_id, o.observed_at, o.position
FROM observations o
WHERE o.id = $2
ON CONFLICT (observation_id) DO NOTHING
`

type AttachObservationToTrackParams struct {
	TrackID       string
	ObservationID string
}

func (q *Queries) AttachObservationToTrack(ctx context.Context, arg AttachObservationToTrackParams) (int64, error) {
	result, err := q.db.Exec(ctx, attachObservationToTrack, arg.TrackID, arg.ObservationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const closeTrack = `-- name: CloseTrack :one
UPDATE tracks
SET status = 'closed', closed_at = now(), updated_at = now()
WHERE id = $1
RETURNING id, external_ref, status, first_seen_at, last_seen_at, metadata, created_at, updated_at, closed_at
`

func (q *Queries) CloseTrack(ctx context.Context, id string) (Track, error) {
	row := q.db.QueryRow(ctx, closeTrack, id)
	var i Track
	err := row.Scan(
		&i.ID,
		&i.ExternalRef,
		&i.Status,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClosedAt,
	)
	return i, err
}

const countObservationsBySourceForTrack = `-- name: CountObservationsBySourceForTrack :many
SELECT source_id, count(*) AS observation_count
FROM track_observations
WHERE track_id = $1
GROUP BY source_id
ORDER BY observation_count DESC
`

type CountObservationsBySourceForTrackRow struct {
	SourceID         string
	ObservationCount int64
}

func (q *Queries) CountObservationsBySourceForTrack(ctx context.Context, trackID string) ([]CountObservationsBySourceForTrackRow, error) {
	rows, err := q.db.Query(ctx, countObservationsBySourceForTrack, trackID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountObservationsBySourceForTrackRow{}
	for rows.Next() {
		var i CountObservationsBySourceForTrackRow
		if err := rows.Scan(&i.SourceID, &i.ObservationCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countTrackObservations = `-- name: CountTrackObservations :one
SELECT count(*) FROM track_observations WHERE track_id = $1
`

func (q *Queries) CountTrackObservations(ctx context.Context, trackID string) (int64, error) {
	row := q.db.QueryRow(ctx, countTrackObservations, trackID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTracks = `-- name: CountTracks :one
SELECT count(*) FROM tracks
`

func (q *Queries) CountTracks(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTracks)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTrack = `-- name: CreateTrack :one
INSERT INTO tracks (id, external_ref, status, first_seen_at, last_seen_at, metadata, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, now(), now())
RETURNING id, external_ref, status, first_seen_at, last_seen_at, metadata, created_at, updated_at, closed_at
`

type CreateTrackParams struct {
	ID          string
	ExternalRef *string
	Status      string
	FirstSeenAt pgtype.Timestamptz
	LastSeenAt  pgtype.Timestamptz
	Metadata    []byte
}

func (q *Queries) CreateTrack(ctx context.Context, arg CreateTrackParams) (Track, error) {
	row := q.db.QueryRow(ctx, createTrack,
		arg.ID,
		arg.ExternalRef,
		arg.Status,
		arg.FirstSeenAt,
		arg.LastSeenAt,
		arg.Metadata,
	)
	var i Track
	err := row.Scan(
		&i.ID,
		&i.ExternalRef,
		&i.Status,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClosedAt,
	)
	return i, err
}

const createTrackHistoryEntry = `-- name: CreateTrackHistoryEntry :exec
INSERT INTO track_history (id, track_id, observed_at, position, speed, heading)
VALUES (
    $1, $2, $3,
    CASE WHEN $4::boolean
         THEN ST_SetSRID(ST_MakePoint($5::float8, $6::float8), 4326)::geography
         ELSE NULL END,
    $7, $8
)
`

type CreateTrackHistoryEntryParams struct {
	ID          string
	TrackID     string
	ObservedAt  pgtype.Timestamptz
	HasPosition bool
	Lng         float64
	Lat         float64
	Speed       *float64
	Heading     *float64
}

func (q *Queries) CreateTrackHistoryEntry(ctx context.Context, arg CreateTrackHistoryEntryParams) error {
	_, err := q.db.Exec(ctx, createTrackHistoryEntry,
		arg.ID,
		arg.TrackID,
		arg.ObservedAt,
		arg.HasPosition,
		arg.Lng,
		arg.Lat,
		arg.Speed,
		arg.Heading,
	)
	return err
}

const findTrackByExternalRef = `-- name: FindTrackByExternalRef :one
SELECT
    t.id, t.external_ref, t.status, t.first_seen_at, t.last_seen_at,
    t.metadata, t.created_at, t.updated_at, t.closed_at,
    s.speed, s.heading, s.updated_at AS state_updated_at,
    (s.position IS NOT NULL)::boolean AS has_position,
    COALESCE(ST_Y(s.position::geometry), 0)::float8 AS lat,
    COALESCE(ST_X(s.position::geometry), 0)::float8 AS lng
FROM tracks t
LEFT JOIN track_state s ON s.track_id = t.id
WHERE t.external_ref = $1
`

type FindTrackByExternalRefRow struct {
	ID             string
	ExternalRef    *string
	Status         string
	FirstSeenAt    pgtype.Timestamptz
	LastSeenAt     pgtype.Timestamptz
	Metadata       []byte
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	ClosedAt       pgtype.Timestamptz
	Speed          *float64
	Heading        *float64
	StateUpdatedAt pgtype.Timestamptz
	HasPosition    bool
	Lat            float64
	Lng            float64
}

func (q *Queries) FindTrackByExternalRef(ctx context.Context, externalRef *string) (FindTrackByExternalRefRow, error) {
	row := q.db.QueryRow(ctx, findTrackByExternalRef, externalRef)
	var i FindTrackByExternalRefRow
	err := row.Scan(
		&i.ID,
		&i.ExternalRef,
		&i.Status,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClosedAt,
		&i.Speed,
		&i.Heading,
		&i.StateUpdatedAt,
		&i.HasPosition,
		&i.Lat,
		&i.Lng,
	)
	return i, err
}

const getTrackDetail = `-- name: GetTrackDetail :one
SELECT
    t.id, t.external_ref, t.status, t.first_seen_at, t.last_seen_at,
    t.metadata, t.created_at, t.updated_at, t.closed_at,
    s.speed, s.heading, s.updated_at AS state_updated_at,
    (s.position IS NOT NULL)::boolean AS has_position,
    COALESCE(ST_Y(s.position::geometry), 0)::float8 AS lat,
    COALESCE(ST_X(s.position::geometry), 0)::float8 AS lng,
    (SELECT count(*) FROM track_observations tobs WHERE tobs.track_id = t.id)::int AS observation_count
FROM tracks t
LEFT JOIN track_state s ON s.track_id = t.id
WHERE t.id = $1
`

type GetTrackDetailRow struct {
	ID               string
	ExternalRef      *string
	Status           string
	FirstSeenAt      pgtype.Timestamptz
	LastSeenAt       pgtype.Timestamptz
	Metadata         []byte
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	ClosedAt         pgtype.Timestamptz
	Speed            *float64
	Heading          *float64
	StateUpdatedAt   pgtype.Timestamptz
	HasPosition      bool
	Lat              float64
	Lng              float64
	ObservationCount int32
}

func (q *Queries) GetTrackDetail(ctx context.Context, id string) (GetTrackDetailRow, error) {
	row := q.db.QueryRow(ctx, getTrackDetail, id)
	var i GetTrackDetailRow
	err := row.Scan(
		&i.ID,
		&i.ExternalRef,
		&i.Status,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClosedAt,
		&i.Speed,
		&i.Heading,
		&i.StateUpdatedAt,
		&i.HasPosition,
		&i.Lat,
		&i.Lng,
		&i.ObservationCount,
	)
	return i, err
}

const listTrackDetails = `-- name: ListTrackDetails :many
SELECT
    t.id, t.external_ref, t.status, t.first_seen_at, t.last_seen_at,
    t.metadata, t.created_at, t.updated_at, t.closed_at,
    s.speed, s.heading, s.updated_at AS state_updated_at,
    (s.position IS NOT NULL)::boolean AS has_position,
    COALESCE(ST_Y(s.position::geometry), 0)::float8 AS lat,
    COALESCE(ST_X(s.position::geometry), 0)::float8 AS lng,
    (SELECT count(*) FROM track_observations tobs WHERE tobs.track_id = t.id)::int AS observation_count
FROM tracks t
LEFT JOIN track_state s ON s.track_id = t.id
ORDER BY t.last_seen_at DESC
LIMIT $2 OFFSET $1
`

type ListTrackDetailsParams struct {
	OffsetCount int32
	LimitCount  int32
}

type ListTrackDetailsRow struct {
	ID               string
	ExternalRef      *string
	Status           string
	FirstSeenAt      pgtype.Timestamptz
	LastSeenAt       pgtype.Timestamptz
	Metadata         []byte
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	ClosedAt         pgtype.Timestamptz
	Speed            *float64
	Heading          *float64
	StateUpdatedAt   pgtype.Timestamptz
	HasPosition      bool
	Lat              float64
	Lng              float64
	ObservationCount int32
}

func (q *Queries) ListTrackDetails(ctx context.Context, arg ListTrackDetailsParams) ([]ListTrackDetailsRow, error) {
	rows, err := q.db.Query(ctx, listTrackDetails, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTrackDetailsRow{}
	for rows.Next() {
		var i ListTrackDetailsRow
		if err := rows.Scan(
			&i.ID,
			&i.ExternalRef,
			&i.Status,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClosedAt,
			&i.Speed,
			&i.Heading,
			&i.StateUpdatedAt,
			&i.HasPosition,
			&i.Lat,
			&i.Lng,
			&i.ObservationCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrackHistory = `-- name: ListTrackHistory :many
SELECT
    id, observed_at, speed, heading,
    (position IS NOT NULL)::boolean AS has_position,
    COALESCE(ST_Y(position::geometry), 0)::float8 AS lat,
    COALESCE(ST_X(position::geometry), 0)::float8 AS lng
FROM track_history
WHERE track_id = $1
ORDER BY observed_at ASC, id ASC
LIMIT $2
`

type ListTrackHistoryParams struct {
	TrackID    string
	LimitCount int32
}

type ListTrackHistoryRow struct {
	ID          string
	ObservedAt  pgtype.Timestamptz
	Speed       *float64
	Heading     *float64
	HasPosition bool
	Lat         float64
	Lng         float64
}

func (q *Queries) ListTrackHistory(ctx context.Context, arg ListTrackHistoryParams) ([]ListTrackHistoryRow, error) {
	rows, err := q.db.Query(ctx, listTrackHistory, arg.TrackID, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTrackHistoryRow{}
	for rows.Next() {
		var i ListTrackHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.ObservedAt,
			&i.Speed,
			&i.Heading,
			&i.HasPosition,
			&i.Lat,
			&i.Lng,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchTrack = `-- name: TouchTrack :exec
UPDATE tracks
SET last_seen_at = GREATEST(last_seen_at, $1), updated_at = now()
WHERE id = $2
`

type TouchTrackParams struct {
	ObservedAt pgtype.Timestamptz
	ID         string
}

func (q *Queries) TouchTrack(ctx context.Context, arg TouchTrackParams) error {
	_, err := q.db.Exec(ctx, touchTrack, arg.ObservedAt, arg.ID)
	return err
}

const upsertTrackState = `-- name: UpsertTrackState :exec
INSERT INTO track_state (track_id, position, speed, heading, updated_at)
VALUES (
    $1,
    CASE WHEN $2::boolean
         THEN ST_SetSRID(ST_MakePoint($3::float8, $4::float8), 4326)::geography
         ELSE NULL END,
    $5, $6, now()
)
ON CONFLICT (track_id) DO UPDATE SET
    position = CASE WHEN $2::boolean THEN EXCLUDED.position ELSE track_state.position END,
    speed = COALESCE(EXCLUDED.speed, track_state.speed),
    heading = COALESCE(EXCLUDED.heading, track_state.heading),
    updated_at = now()
`

type UpsertTrackStateParams struct {
	TrackID     string
	HasPosition bool
	Lng         float64
	Lat         float64
	Speed       *float64
	Heading     *float64
}

func (q *Queries) UpsertTrackState(ctx context.Context, arg UpsertTrackStateParams) error {
	_, err := q.db.Exec(ctx, upsertTrackState,
		arg.TrackID,
		arg.HasPosition,
		arg.Lng,
		arg.Lat,
		arg.Speed,
		arg.Heading,
	)
	return err
}
